import 'dart:convert';

import 'package:flutter/services.dart';
import 'package:flutter/widgets.dart';

class AppLocalizations {
  final Locale locale;
  final Map<String, String> _strings;

  const AppLocalizations(this.locale, this._strings);

  static const delegate = _AppLocalizationsDelegate();

  static AppLocalizations of(BuildContext context) {
    final localizations = Localizations.of<AppLocalizations>(
      context,
      AppLocalizations,
    );
    assert(localizations != null, 'AppLocalizations not found in context');
    return localizations!;
  }

  String t(String key) {
    final value = _strings[key];
    if (value != null) return value;

    final fallback = locale.languageCode == 'lo' || locale.languageCode == 'la'
        ? _laFallbacks[key]
        : _enFallbacks[key];
    return fallback ?? key;
  }

  static Future<AppLocalizations> load(Locale locale) async {
    final languageCode = _assetCode(locale.languageCode);
    final json = await rootBundle.loadString(
      'assets/l10n/app_$languageCode.arb',
      cache: false,
    );
    final values = jsonDecode(json) as Map<String, dynamic>;
    final strings = <String, String>{};

    for (final entry in values.entries) {
      if (entry.key.startsWith('@')) continue;
      final value = entry.value;
      if (value is String) strings[entry.key] = value;
    }

    return AppLocalizations(locale, strings);
  }

  static String _assetCode(String languageCode) {
    if (languageCode == 'lo' || languageCode == 'la') return 'la';
    return 'en';
  }

  static const Map<String, String> _enFallbacks = {
    'studentsCardViewCount': 'Card view • {count} students',
    'noStudentsYet': 'No students yet',
    'addChildToGetStarted': "Let's add your child to get started.",
    'emptyStudentsTip':
        'Tip: tap “Add student” below and fill in your child’s information to link them to your account. Once submitted, an admin will review and approve.',
    'addStudent': 'Add student',
    'addAStudent': 'Add a student',
    'submitStudentApplicationHint':
        'Submit a new application — admin will review it.',
    'student': 'Student',
    'studentInformationTitle': 'Student Information',
    'studentInformationSubtitle':
        'Tell us about your child. Fields marked * are required.',
    'studentStepOf': 'STEP {step} OF 6',
    'branch': 'Branch',
    'selectBranch': 'Select branch',
    'loadingBranches': 'Loading branches...',
    'education': 'Education',
    'sibling': 'Sibling',
    'liveWith': 'Live With',
    'emergency': 'Emergency',
    'skip': 'Skip',
    'submitApplication': 'Submit application',
    'selectPlaceholder': 'Select...',
    'useSavedDetails': 'Use saved details',
    'useSavedDetailsSubtitle':
        'Fill household address, living-with and emergency contacts.',
    'use': 'Use',
    'studentHealth': 'Student Health',
    'studentHealthOptionHint':
        'Select this option only if it applies to the student.',
    'physicalMobilityDisabilities': 'Physical and Mobility Disabilities',
    'sensoryDisabilities': 'Sensory Disabilities',
    'intellectualCognitiveDisabilities':
        'Intellectual and Cognitive Disabilities',
    'neurodevelopmentalLearningDisabilities':
        'Neurodevelopmental and Learning Disabilities',
    'psychiatricMentalHealthDisabilities':
        'Psychiatric and Mental Health Disabilities',
    'chronicInvisibleDisabilities':
        'Chronic Illnesses and Invisible Disabilities',
    'placeOfBirth': 'Place of Birth',
    'villageOfBirth': 'Village of Birth',
    'provinceOfBirth': 'Province of Birth',
    'districtOfBirth': 'District of Birth',
    'currentAddress': 'Current Address',
    'educationHistoryKindergarten': 'Education History — Kindergarten',
    'primaryHistory': 'Primary History',
    'yearLevel': 'Year / Level',
    'school': 'School',
    'enterSchoolName': 'Enter school name',
    'addSibling': 'Add a sibling',
    'addAnotherSibling': 'Add another sibling',
    'noSiblingsAddedYet': 'No siblings added yet',
    'siblingsEmptyHint':
        'Add brothers or sisters who are direct relatives of the student, or skip this step.',
    'siblingUpper': 'SIBLING',
    'fullName': 'Full Name',
    'enterFullName': 'Enter full name',
    'currentSchoolName': 'Current School Name',
    'enterCurrentSchool': 'Enter current school',
    'enterPhone1': 'Enter phone 1',
    'enterPhone2': 'Enter phone 2',
    'dateFormatPlaceholder': 'Day/Month/Year',
    'exampleAcademicYearKindergarten': 'e.g. 2019-2020',
    'exampleKindergartenLevel': 'e.g. K1',
    'exampleAcademicYearPrimary': 'e.g. 2022-2023',
    'examplePrimaryLevel': 'e.g. Grade 1',
    'remove': 'Remove',
    'addPersonLivingWithStudent': 'Add a person living with student',
    'addAnotherPerson': 'Add another person',
    'onePersonRequired': 'At least one person is required',
    'noOneAddedYet': 'No one added yet',
    'livingWithEmptyHint':
        'Add at least one person who lives with the student.',
    'personLivingWithStudentUpper': 'PERSON LIVING WITH STUDENT',
    'tapToExpand': 'Tap to expand',
    'selectLevel': 'Select level',
    'occupation': 'Occupation',
    'enterOccupation': 'Enter occupation',
    'addEmergencyContact': 'Add an emergency contact',
    'addAnotherEmergencyContact': 'Add another emergency contact',
    'oneEmergencyContactRequired': 'At least one emergency contact is required',
    'noEmergencyContactAddedYet': 'No emergency contact added yet',
    'emergencyEmptyHint':
        'Add one or more emergency contacts the school can reach if needed.',
    'emergencyContactUpper': 'EMERGENCY CONTACT',
    'relationshipToStudent': 'Relationship to Student',
    'enterRelationship': 'Enter relationship',
    'hospital': 'Hospital',
    'enterHospitalName': 'Enter hospital name',
    'doctorName': 'Doctor Name',
    'enterDoctorName': 'Enter doctor name',
    'doctorContact': 'Doctor Contact',
    'enterDoctorContact': 'Enter doctor contact',
    'male': 'Male',
    'female': 'Female',
    'other': 'Other',
    'village': 'Village',
    'province': 'Province',
    'district': 'District',
    'enterVillage': 'Enter village',
    'loadingProvinces': 'Loading provinces...',
    'couldNotLoadProvinces': 'Could not load provinces',
    'selectProvince': 'Select province',
    'selectProvinceFirst': 'Select province first',
    'selectDistrict': 'Select district',
    'selectDistrictFirst': 'Select district first',
    'selectVillage': 'Select village',
    'academicYear': 'Academic year',
    'temporaryPlatformNoticeButton': 'Special notice',
    'temporaryPlatformNoticeTitle': 'Temporary web access',
    'temporaryPlatformNoticeBody':
        'This web platform is available temporarily so you can continue using the school system now. Soon, Sivatthana Application will become the main channel for school updates and services. Download the app from the App Store or Google Play when it is available.',
    'temporaryPlatformNoticeStoreLabel': 'Available soon on',
    'educationLevel': 'Education Level',
    'workplace': 'Workplace',
    'enterWorkplace': 'Enter workplace',
    'email': 'Email',
    'enterEmail': 'Enter email',
    'phoneNo1': 'Phone No. 1',
    'phoneNo2': 'Phone No. 2',
    'enterPhoneNumber': 'Enter phone 020XXXXXXXX',
    'idCardNo': 'ID Card No.',
    'enterIdCardNumber': 'Enter ID card no.',
    'passportNo': 'Passport No.',
    'enterPassportNumber': 'Enter passport no.',
    'familyBookNo': 'Family Book No.',
    'enterFamilyBookNumber': 'Enter family book no.',
    'identityCard': 'Identity card image',
    'familyBookUpload': 'Family book image (PDF or image)',
    'nationality': 'Nationality',
    'enterNationality': 'Enter nationality',
    'ethnicity': 'Ethnicity',
    'enterEthnicity': 'Enter ethnicity',
    'religion': 'Religion',
    'enterReligion': 'Enter religion',
    'homeNo': 'House No.',
    'enterHomeNumber': 'Enter house no.',
    'homeUnit': 'House Unit',
    'enterUnitRoom': 'Enter unit / room',
    'mobilityDisability': 'Mobility disability',
    'difficultyWalkingStairs': 'Difficulty walking or using stairs',
    'requiresMobilityAids': 'Often requiring wheelchairs, walkers, or canes.',
    'amputationLimbDifferences': 'Amputation and Limb Differences',
    'neuromuscularConditions': 'Neuromuscular Conditions',
    'missingLimbsDetail':
        'Missing limbs from birth, accidents, or medical procedures.',
    'cerebralPalsy': 'Cerebral Palsy',
    'muscularDystrophy': 'Muscular Dystrophy',
    'multipleSclerosis': 'Multiple Sclerosis',
    'spinalCordInjuries': 'Spinal Cord Injuries',
    'partialSpinalTrauma': 'Trauma to the spine resulting in partial pain',
    'fullSpinalParalysis': 'Trauma to the spine resulting in full paralysis',
    'visualDifferences': 'Visual differences',
    'lowVisionDetail': 'Low vision not correctable by glasses',
    'legalBlindness': 'Legal blindness',
    'totalBlindness': 'Total blindness',
    'colourblindness': 'Colourblindness',
    'albinismAniridia': 'Albinism or aniridia',
    'hearingLoss': 'Hearing loss',
    'mildHearingLoss': 'Mild hearing loss (cannot hear soft sounds)',
    'moderateHearingLoss':
        'Moderate hearing loss (struggles to hear normal speech)',
    'severeHearingLoss': 'Severe hearing loss (cannot hear speech)',
    'profoundDeafness':
        'Profound deafness (cannot hear speech and only detects very loud sounds)',
    'sensoryProcessingDifferences': 'Sensory Processing Differences',
    'interoceptionDetail':
        'Interoception (Internal Senses): Processing internal bodily signals like heart rate, hunger, thirst, and the need to use the restroom.',
    'mildIntellectualDisability': 'Mild intellectual disability',
    'moderateIntellectualDisability': 'Moderate intellectual disability',
    'severeIntellectualDisability': 'Severe intellectual disability',
    'traumaticBrainInjuries': 'Traumatic Brain Injuries (TBI)',
    'hypoxicAnoxicBrainInjury': 'Hypoxic/Anoxic Brain Injury',
    'stroke': 'Stroke',
    'specificLearningDisabilities': 'Specific Learning Disabilities',
    'specificLearningDescription':
        'Difficulties with specific academic skills, such as',
    'dyslexiaReading': 'Dyslexia (reading)',
    'dyscalculiaMath': 'Dyscalculia (math)',
    'dysgraphiaWriting': 'Dysgraphia (writing)',
    'autismSpectrumDisorder': 'Autism Spectrum Disorder (ASD)',
    'adhd': 'ADHD',
    'foetalAlcoholSpectrumDisorders': 'Foetal alcohol spectrum disorders',
    'developmentalLanguageDisorder': 'Developmental language disorder',
    'moodDisorders': 'Mood Disorders',
    'majorDepressiveDisorder': 'Major Depressive Disorder',
    'bipolarDisorder': 'Bipolar Disorder.',
    'anxietyDisorders': 'Anxiety Disorders',
    'severeAnxiety': 'Severe anxiety',
    'panicDisorder': 'Panic Disorder',
    'obsessiveCompulsiveDisorder': 'Obsessive-Compulsive Disorder (OCD)',
    'postTraumaticStressDisorder': 'Post-Traumatic Stress Disorder (PTSD)',
    'respiratoryCardiovascularConditions':
        'Respiratory and Cardiovascular Conditions',
    'severe': 'Severe',
    'asthma': 'Asthma',
    'chooseAddStudentMethod': "Choose how you'd like to add your child.",
    'fillInForm': 'Fill in a form',
    'fillInFormSubtitle': "Enter your child's information yourself.",
    'scanQrCode': 'Scan QR code',
    'scanQrCodeSubtitle': 'Add a student using a QR code from the school.',
    'cameraError': 'Camera error: {error}',
    'cameraNeedsHttpsWeb':
        'Camera needs HTTPS on web. Open UAT at https://app.classroomconnect.la/alpha-app-uat/',
    'cameraPermissionDenied':
        'Camera permission was denied. Please allow camera access and try again.',
    'cameraScannerUnsupported':
        'Camera scanner is not supported by this browser or device.',
    'invalidStudentQrCode': "This doesn't look like a valid student QR code.",
    'sessionMissingSignInAgain':
        'Your session is missing. Please sign in again.',
    'sessionMissingResubmit':
        'Your session is missing. Please sign in again to resubmit.',
    'sessionMissingAddStudent':
        'Your session is missing. Please sign in again to add a student.',
    'unableToConnectTryAgain': 'Unable to connect. Please try again.',
    'submittingRequest': 'Submitting request...',
    'processing': 'Processing...',
    'alignStudentQrCodeFrame': "Align the student's QR code inside the frame",
    'scannerReadsAutomatically':
        'The scanner reads automatically on detection.',
    'attendanceQrCheckIn': 'Attendance • QR Check-in',
    'askOtherGuardianQrProfile':
        "Ask the student's other guardian to show their QR code from the Profile page.",
    'addStudentQrLinkRequest': 'Add student • QR link request',
    'cantSendRequest': "Can't send this request",
    'scanAgain': 'Scan Again',
    'studentLinkedToAccount': '{name} has been linked to your account.',
    'studentPendingAdminApproval': 'This student is pending admin approval.',
    'studentApprovedMessage': '{name} has been approved.',
    'applicationDeleted': 'Application deleted.',
    'couldNotOpenResubmitStudentMissing':
        'Could not open resubmit form. Student ID missing.',
    'addAnotherStudent': 'Add another student',
    'comingSoon': 'Coming soon',
    'somethingWentWrong': 'Something went wrong',
    'tryAgain': 'Try Again',
    'requestSent': 'REQUEST SENT',
    'qrLinkRequestReviewMessage':
        'An admin will review your request. Once approved, this student will show up in your account.',
    'done': 'Done',
    'pendingApproval': 'Pending Approval',
    'pendingApprovalUpper': 'PENDING APPROVAL',
    'studentSubmitted': 'Student Submitted',
    'linkRequestSubmitted': 'Link Request Submitted',
    'studentRejectedTitle': 'Student Rejected',
    'linkRequestRejectedTitle': 'Link Request Rejected',
    'thankYouNamePrefix': 'Thank you, ',
    'studentSubmittedMessage':
        '. Your application has been received and is now waiting for admin approval.',
    'linkRequestSubmittedMessage':
        '. Your request to link this student is waiting for admin approval.',
    'studentRejectedMessage':
        '. Admin reviewed this application and requested changes.',
    'linkRequestRejectedMessage':
        '. Admin reviewed this link request and rejected it.',
    'qrLinkRequestReceived': 'QR link request received',
    'adminRejectedRequest': 'Admin rejected the request',
    'closed': 'Closed',
    'studentWillAppearAfterApproval': 'Student will appear after approval',
    'backToStudents': 'Back to students',
    'parentApplicationSubmittedTitle': 'Application Submitted',
    'parentApplicationSubmittedAlertTitle': 'Application submitted',
    'parentApplicationSubmittedAlertMessage':
        'Your parent information has been submitted. Please wait for admin approval before signing in.',
    'parentApplicationApprovedAlertTitle': 'Application approved',
    'parentApplicationApprovedAlertMessage':
        'Your application has been approved. You can now sign in with your email and password.',
    'parentApplicationRejectedAlertTitle': 'Application rejected',
    'parentApplicationRejectedDefaultMessage':
        'Admin rejected your parent application. Please review your information and submit again.',
    'submissionFailed': 'Submission failed',
    'resubmittingApplication': 'Resubmitting application...',
    'addingStudent': 'Adding student...',
    'couldNotResolveParentId': 'Could not resolve parent ID from response.',
    'studentRejectedAlertTitle': 'Student rejected',
    'linkRequestRejectedAlertTitle': 'Link request rejected',
    'studentRejectedDefaultMessage':
        'Admin rejected {name}. Please review the student information and submit again.',
    'linkRequestRejectedDefaultMessage':
        'Admin rejected the request to link {name} to your account.',
    'reviewStudentInformationAndSubmitAgain':
        'Please review the student information and submit again.',
    'submitPreviousStudentApplicationFirst':
        'Submit a previous student application first to save household details.',
    'savedStudentDetailsAppliedMessage':
        'Your household address, living-with and emergency contact details have been filled in.',
    'possibleDuplicate': 'Possible duplicate',
    'possibleDuplicateMessage':
        'A student named {names} is already registered under this account. Add this student anyway?',
    'addAnyway': 'Add anyway',
    'preparingApplication': 'Preparing your application...',
    'convertingFamilyBookSingle': 'Converting Family Book image to PDF...',
    'convertingFamilyBookMany':
        'Converting {count} Family Book images to PDF...',
    'submittingApplication': 'Submitting your application...',
    'couldNotResolveApplicationId': 'Could not resolve your application ID.',
    'noSavedDetailsYet': 'No saved details yet',
    'submitPreviousApplicationFirst':
        'Submit a previous application first to save your contact, identity and address details.',
    'savedDetailsApplied': 'Saved details applied',
    'savedParentDetailsAppliedMessage':
        'Your saved contact, identity and address details have been filled in. Step 1 remains private and must be completed again.',
    'fillSavedParentDetails':
        'Fill saved contact, identity and address details.',
    'pleaseWait': 'Please wait',
    'couldNotReadFile': 'Could not read this file',
    'pdf': 'PDF',
    'image': 'Image',
    'choosePdfOrImages': 'Choose PDF or images',
    'chooseEitherPdfOrImagesNotBoth':
        'Please choose either PDF or images, not both.',
    'chooseOnlyOnePdfFile': 'Please choose only one PDF file.',
    'choosePdfJpgJpegPngFiles': 'Please choose PDF, JPG, JPEG, or PNG files.',
    'choosePdf': 'Choose PDF',
    'chooseImage': 'Choose image',
    'tapToAddMore': 'tap to add more',
    'convertedToPdf': '{name} -> PDF',
    'imagesConvertedToPdf': '{count} images -> PDF',
    'reasonFromAdmin': 'Reason from admin',
    'parentApplicationThanks': 'Thank you',
    'parentApplicationWaitingMessage':
        'Your application has been received and is now waiting for admin approval.',
    'checkingStatus': 'Checking status...',
    'checkApprovalStatus': 'Check approval status',
    'checkAgain': 'Check again',
    'backToSignIn': 'Back to Sign In',
    'cancelApplication': 'Cancel application',
    'cancelApplicationQuestion': 'Cancel application?',
    'cancelApplicationMessage':
        'Your local pending status will be cleared. The backend record remains until admin removes it.',
    'yourLogin': 'YOUR LOGIN',
    'password': 'Password',
    'notAvailable': 'Not available',
    'passwordUnavailable': 'Password unavailable',
    'passwordUnavailableMessage':
        'This application was submitted before the password was stored locally. Cancel the application and re-submit to see your login password.',
    'savePasswordHint':
        'Save this password. You can change it after admin approves your account.',
    'hide': 'Hide',
    'show': 'Show',
    'submitted': 'Submitted',
    'applicationReceived': 'Application received',
    'pendingReview': 'Pending Review',
    'adminRequestedChanges': 'Admin requested changes',
    'waitingForAdminApproval': 'Waiting for admin approval',
    'approved': 'Approved',
    'accountApprovedUpper': 'ACCOUNT APPROVED',
    'youreApproved': "You're approved!",
    'welcome': 'Welcome',
    'accountApprovedMessage':
        'Your account is now active. You can sign in any time using the email and password you submitted.',
    'goToSignIn': 'Go to sign in',
    'resubmit': 'Resubmit',
    'updateDetailsAndSendAgain': 'Update details and send again',
    'editAndResubmit': 'Edit and resubmit',
    'notifiedOnceApproved': "You'll be notified once approved",
    'qrLinkPending': 'QR Link Pending',
    'rejected': 'Rejected',
    'rejectedUpper': 'REJECTED',
    'applicationRejected': 'Application Rejected',
    'applicationRejectedMessage':
        'Admin reviewed this application and requested changes.',
    'reviewParentInformationAndSubmitAgain':
        'Please review your parent information and submit again.',
    'logout': 'Logout',
    'logoutConfirmMessage': 'Do you want to logout and go to Login page?',
    'cancel': 'Cancel',
    'settings': 'Settings',
    'account': 'Account',
    'emergencyContact': 'Emergency contact',
    'addContact': 'Add contact',
    'editContact': 'Edit contact',
    'saveChanges': 'Save changes',
    'job': 'Job',
    'workingPlace': 'Working place',
    'doctor': 'Doctor',
    'ok': 'OK',
    'edit': 'Edit',
    'saved': 'Saved',
    'saveFailed': 'Save failed',
    'missingInformation': 'Missing information',
    'nameAndPhoneRequired': 'Name and Phone #1 are required.',
    'couldNotLoadEmergencyContact': 'Could not load emergency contact.',
    'couldNotSaveEmergencyContact': 'Could not save emergency contact.',
    'couldNotSaveEmergencyContactTryAgain':
        'Could not save emergency contact. Please try again.',
    'limitReached': 'Limit reached',
    'maxEmergencyContactsOnly': 'You can add up to 5 emergency contacts only.',
    'emergencyContactAdded': 'Emergency contact added.',
    'contactUpdated': 'Contact updated',
    'emergencyContactSaved': 'Emergency contact information has been saved.',
    'deleteContactQuestion': 'Delete contact?',
    'removeEmergencyContactMessage': 'Remove {name} from emergency contacts.',
    'contactDeleted': 'Contact deleted',
    'contactRemovedMessage': '{name} has been removed.',
    'priorityUpdated': 'Priority updated.',
    'noEmergencyContactFound': 'No emergency contact found.',
    'noAdditionalDetails': 'No additional details.',
    'moveHigherPriority': 'Move higher priority',
    'moveLowerPriority': 'Move lower priority',
    'language': 'Language',
    'english': 'English',
    'lao': 'Lao',
    'profile': 'Profile',
    'profileSettings': 'Profile Settings',
    'profileSettingsSubtitle': 'Update and modify your profile',
    'privacy': 'Privacy',
    'privacySubtitle': 'Change your password',
    'notificationsSubtitle': 'Change your notification settings',
    'generalUpper': 'GENERAL',
    'studentQrCode': 'Student QR Code',
    'saveQrCode': 'Save QR code',
    'saving': 'Saving...',
    'savingQrCode': 'Saving QR code...',
    'qrCodeNotReady': 'QR code is not ready yet.',
    'qrCodeCouldNotBeSaved': 'The QR code could not be saved.',
    'qrCodeSaved': 'QR code saved',
    'qrCodeSavedToGallery': 'The QR code was saved to your gallery.',
    'qrCodeSavedSuccessfully': 'The QR code was saved successfully.',
    'couldNotSaveQrCode': 'Could not save QR code',
    'error': 'Error',
    'contactCountOne': '{count} contact',
    'contactCountMany': '{count} contacts',
    'selectLanguage': 'Select language',
    'fieldRequiredError': 'This field is required',
    'validEmailError': 'Enter a valid email',
    'passwordMinLengthError': 'Password must be at least 6 characters',
    'passwordsDoNotMatchError': 'Passwords do not match',
    'uploadDocumentError': 'Please upload this document',
    'contactSchool': 'Contact school',
    'getInTouch': 'Get in touch',
    'findUsOnline': 'Find us online',
    'phone1Label': 'Phone #1',
    'phone2Label': 'Phone #2',
    'branchCode': 'Branch Code',
    'governanceBranchId': 'Governance Branch ID',
    'location': 'Location',
    'googleMaps': 'Google Maps',
    'facebook': 'Facebook',
    'website': 'Website',
    'schoolBranch': 'School branch',
    'copied': 'Copied',
    'couldNotOpenLink': 'Could not open this link',
    'couldNotLoadSchoolInfo': "Couldn't load school info",
    'noSchoolInfoAvailable': 'No school info available',
    'noBranchLinkedStudent': 'No branch is linked to the selected student.',
    'homeTab': 'Home',
    'classroomTab': 'Classroom',
    'studyResultTab': 'Study Results',
    'feeTab': 'Fees',
    'scoreTab': 'Scores',
    'settingsTab': 'Settings',
    'homeCreateTask': 'Create task',
    'homeQuickPayment': 'Quick payment',
    'homeNewAppointment': 'New appointment',
    'couldNotLoadParentSession': 'Could not load parent session.',
    'noApprovedStudentsFound': 'No approved students found.',
    'couldNotLoadStudents': 'Could not load students',
    'classNotAssigned': 'Class not assigned',
    'notifications': 'Notifications',
    'noNotifications': 'No notifications',
    'noNotificationsHint': 'New notifications will appear here.',
    'notification': 'Notification',
    'unread': 'Unread',
    'read': 'Read',
    'unreadCount': '{count} unread',
    'allCaughtUp': 'All caught up',
    'trySwitchingFilter': 'Try switching the filter.',
    'copy': 'Copy',
    'details': 'Details',
    'markAsRead': 'Mark as Read',
    'markAsUnread': 'Mark as Unread',
    'viewAll': 'View all',
    'tapOutsideToClose': 'Tap outside to close',
    'recent': 'Recent',
    'none': '-',
    'today': 'Today',
    'yesterday': 'Yesterday',
    'thisWeek': 'This week',
    'earlier': 'Earlier',
    'checkInLate': 'Check-in Late',
    'checkedIn': 'Checked-In',
    'notCheckedIn': 'Not Checked-In',
    'attendanceTracking': 'Attendance tracking',
    'participationScore': 'Participation score',
    'commonEraPrefix': 'AD',
    'monthJanuary': 'January',
    'monthFebruary': 'February',
    'monthMarch': 'March',
    'monthApril': 'April',
    'monthMay': 'May',
    'monthJune': 'June',
    'monthJuly': 'July',
    'monthAugust': 'August',
    'monthSeptember': 'September',
    'monthOctober': 'October',
    'monthNovember': 'November',
    'monthDecember': 'December',
    'eventAndAnnouncement': 'Event & Announcement',
    'attendanceAndCalendar': 'Attendance & Calendar',
    'laoNewYear2026': 'Lao New Year 2026',
    'allMenus': 'All menus',
    'schoolContact': 'School contact',
    'savingDeposit': 'Savings deposit',
    'savings': 'Savings',
    'studentSavingActivity': 'Student saving activity',
    'yourChild': 'Your child',
    'personalSavings': 'Personal',
    'classroomSavings': 'Classroom',
    'transaction': 'Transaction',
    'amountBalance': 'Amount / Balance',
    'noDataInSelectedRange': 'No data in selected range',
    'tryAnotherDateRangeOrRefresh':
        'Try another date range or refresh this page.',
    'latestDeposit': 'Latest deposit',
    'depositMovement': 'Deposit movement',
    'withdrawalMovement': 'Withdrawal movement',
    'available': 'Available',
    'nonAvailable': 'Non-available',
    'endingBalance': 'Ending balance',
    'withdrawMoney': 'Withdraw money',
    'deposit': 'Deposit',
    'withdrawal': 'Withdrawal',
    'pendingWithdrawal': 'Pending withdrawal',
    'withdrawUpper': 'WITHDRAW',
    'trackingUpper': 'TRACKING',
    'cashReceived': 'Cash received',
    'schoolReleasedWithdrawal':
        'The school has released your withdrawal. Enjoy!',
    'completedUpper': 'COMPLETED',
    'requestRejected': 'Request rejected',
    'schoolCouldNotProcessWithdrawal':
        'The school could not process this withdrawal. Please contact the office for details.',
    'approvedReadyForPickup': 'Approved — ready for pickup',
    'visitOfficeCollectCash':
        'Visit the school office to collect the cash. The teacher will hand it over and confirm.',
    'readyForPickupUpper': 'READY FOR PICKUP',
    'adminConfirmed': 'Admin confirmed',
    'requestForwardedSuperAdmin':
        'Your request was reviewed and forwarded to the super admin for final approval.',
    'waitingSuperAdminUpper': 'WAITING SUPER ADMIN',
    'sendSuccessfully': 'Send successfully',
    'withdrawalRequestReceived':
        'Your withdrawal request was received. The school will review it shortly.',
    'pendingReviewUpper': 'PENDING REVIEW',
    'requestReceivedBySystem': 'Request received by the system',
    'waitingAdminConfirm': 'Waiting for admin to confirm',
    'forwardedToSuperAdmin': 'Forwarded to super admin',
    'superAdminApproved': 'Super admin approved',
    'withdrawalComplete': 'Withdrawal complete',
    'contactSchoolNextSteps': 'Contact the school for next steps',
    'backToSavings': 'Back to savings',
    'checkStatus': 'Check status',
    'close': 'Close',
    'allTransactions': 'All transactions',
    'anyDate': 'Any',
    'search': 'Search',
    'retry': 'Retry',
    'studentIdUnavailableSelectStudentAgain':
        'Student ID is unavailable. Please select the student again.',
    'unableToWithdraw': 'Unable to withdraw',
    'noAvailableBalanceToWithdraw':
        'There is no available balance to withdraw yet.',
    'loadingWithdrawalReasons': 'Loading withdrawal reasons...',
    'noActiveWithdrawalReason':
        'No active withdrawal reason is configured by the school.',
    'withdraw': 'Withdraw',
    'amountNotAvailable': 'Amount not available',
    'youCanWithdrawUpToOnly': 'You can withdraw up to {amount} only.',
    'confirmWithdrawal': 'Confirm withdrawal',
    'requestWithdrawalOf': 'Request withdrawal of {amount}?',
    'submittingWithdrawalRequest': 'Submitting withdrawal request...',
    'withdrawalFailed': 'Withdrawal failed',
    'amountToWithdraw': 'Amount to withdraw',
    'tellSchoolWithdrawalAmount': 'Tell the school how much to release.',
    'nonAvailableFundsHelp':
        'Non-available funds are deposits not yet confirmed by the bank and can\'t be withdrawn yet.',
    'optional': 'OPTIONAL',
    'enterAmountGreaterThanZero': 'Enter an amount greater than zero',
    'exceedsAvailableBalance': 'Exceeds your available balance',
    'percentOfAvailable': '{percent}% of available',
    'anythingSchoolShouldKnow': 'Anything the school should know?',
    'continueAction': 'Continue',
    'newsAndActivities': 'News & Activities',
    'photoGallery': 'Photo gallery',
    'gallery': 'Gallery',
    'allPosts': 'All Post',
    'publicPosts': 'Public Post',
    'individualPosts': 'Individual Post',
    'searchPostsEventsAlbums': 'Search posts, events, or albums...',
    'privatePhotosSharedWithFamily':
        'Private photos are shared by teachers only with your family.',
    'sharedPrivatelyWithFamily': 'Shared privately with your family',
    'studentsTagged': '{count} students tagged',
    'private': 'Private',
    'public': 'Public',
    'noGalleryPostsYet': 'No {tab} yet',
    'newSchoolMomentsAppearHere': 'New school moments will appear here.',
    'couldNotLoadGallery': 'We could not load the gallery right now.',
    'schoolMoment': 'School moment',
    'justNow': 'Just now',
    'minutesAgo': '{count}m ago',
    'hoursAgo': '{count}h ago',
    'daysAgo': '{count}d ago',
    'unableToSendComment': 'Unable to send your comment. Please try again.',
    'imageDownloadedSuccessfully': 'Image downloaded successfully.',
    'unableToDownloadImage': 'Unable to download this image.',
    'downloadImage': 'Download image',
    'likeCountOne': '{count} Like',
    'likeCountMany': '{count} Likes',
    'commentCountOne': '{count} Comment',
    'commentCountMany': '{count} Comments',
    'commentsCount': 'Comments ({count})',
    'category': 'Category',
    'audience': 'Audience',
    'yourFamily': 'Your family',
    'schoolCommunity': 'School community',
    'shared': 'Shared',
    'noCommentsYetStartConversation':
        'No comments yet. Start the conversation!',
    'replyingToName': 'Replying to {name}',
    'replyingToComment': 'Replying to comment',
    'writeAComment': 'Write a comment...',
    'appointments': 'Appointments',
    'calendar': 'Calendar',
    'scheduleAppointments': 'Schedule & Appointments',
    'filter': 'Filter',
    'filterByStatus': 'Filter by status',
    'all': 'All',
    'confirmed': 'Confirmed',
    'cancelled': 'Cancelled',
    'postponed': 'Postponed',
    'pending': 'Pending',
    'accepted': 'Accepted',
    'rescheduled': 'Rescheduled',
    'teacher': 'Teacher',
    'admin': 'Admin',
    'superAdmin': 'Super admin',
    'superSuperAdmin': 'Super super admin',
    'parent': 'Parent',
    'confirm': 'Confirm',
    'delete': 'Delete',
    'reschedule': 'Reschedule',
    'timeline': 'Timeline',
    'noMoreAppointmentsToday': 'No more appointments today',
    'allCaughtUpEnjoyDay': 'Enjoy your day! You\'re all caught up.',
    'loadingAppointments': 'Loading appointments...',
    'couldNotLoadAppointments': 'Could not load appointments',
    'confirmAppointment': 'Confirm Appointment',
    'confirmAppointmentQuestion': 'Confirm',
    'scheduledOn': 'scheduled on',
    'confirming': 'Confirming...',
    'confirmedSuccessTitle': 'Confirmed!',
    'appointmentConfirmedSuccessfully':
        'The appointment has been confirmed successfully.',
    'failed': 'Failed',
    'couldNotConfirmAppointment':
        'Could not confirm the appointment. Please try again.',
    'confirmReschedule': 'Confirm Reschedule',
    'moveAppointmentTo': 'Move appointment to',
    'rescheduling': 'Rescheduling...',
    'rescheduledSuccessTitle': 'Rescheduled!',
    'appointmentMovedTo': 'Appointment has been moved to',
    'couldNotRescheduleAppointment':
        'Could not reschedule the appointment. Please try again.',
    'deleteAppointment': 'Delete Appointment',
    'declineAppointment': 'Decline Appointment',
    'decline': 'Decline',
    'keep': 'Keep',
    'deleting': 'Deleting...',
    'declining': 'Declining...',
    'appointmentDeleted': 'Appointment deleted',
    'appointmentDeclined': 'Appointment declined',
    'couldNotDeleteAppointment':
        'Could not delete the appointment. Please try again.',
    'couldNotDeclineAppointment':
        'Could not decline the appointment. Please try again.',
    'savingAppointment': 'Saving appointment...',
    'appointmentCreated': 'Appointment Created',
    'appointmentSavedSuccessfully':
        'The appointment has been saved successfully.',
    'couldNotSaveAppointment':
        'Could not save the appointment. Please try again.',
    'activityTimeline': 'Activity timeline',
    'updateSingular': 'update',
    'updatePlural': 'updates',
    'noTimelineActivityYet': 'No timeline activity yet.',
    'appointmentRecordCreated': 'Appointment record created',
    'created': 'Created',
    'createdBy': 'Created by',
    'titleLabel': 'Title',
    'scheduleRecorded': 'Schedule recorded',
    'time': 'Time',
    'participantInvited': 'Participant invited',
    'addedAsParticipant': 'added as participant',
    'initialStatus': 'Initial status',
    'appointmentRescheduled': 'Appointment rescheduled',
    'newSchedule': 'New schedule',
    'previous': 'Previous',
    'participantNotifiedOfNewSchedule': 'Participant notified of new schedule',
    'newScheduleSharedWith': 'New schedule shared with',
    'rescheduleRequested': 'Reschedule requested',
    'participantDeclined': 'Participant declined',
    'participantAccepted': 'Participant accepted',
    'requestedDifferentSchedule': 'Requested a different schedule',
    'responseChangedTo': 'Response changed to',
    'by': 'By',
    'proposed': 'Proposed',
    'attempts': 'Attempts',
    'moreDetailSingular': 'more detail',
    'moreDetailPlural': 'more details',
    'timeNotRecorded': 'Time not recorded',
    'pickNewDateTime': 'Pick a new date & time',
    'newDate': 'New Date',
    'newTime': 'New Time',
    'start': 'START',
    'end': 'END',
    'newAppointment': 'New Appointment',
    'parentTeacherMeetingHint': 'e.g. Parent-Teacher Meeting',
    'startAt': 'Start At',
    'endAt': 'End At',
    'meetingPlaceOptional': 'Meetings Place (optional)',
    'addMeetingPlace': 'Add a meeting place...',
    'inviteParentsOptional': 'Invite Parents (optional)',
    'employeesRequired': 'Employees *',
    'saveAppointment': 'Save Appointment',
    'loadingEmployees': 'Loading employees...',
    'selectEmployees': 'Select employees',
    'loadingParents': 'Loading parents...',
    'inviteParents': 'Invite parents',
    'pleaseSelectAtLeastOneEmployee': 'Please select at least one employee',
    'alreadyBooked': 'Already booked',
    'byParent': 'By Parent',
    'byStudent': 'By Student',
    'searchStudentByName': 'Search student by name...',
    'searchParentByName': 'Search parent by name...',
    'noParentsFound': 'No parents found.',
    'typeStudentNameToFindParents':
        'Type a student name to find their parents.',
    'noStudentsFound': 'No students found.',
    'deselectAll': 'Deselect All',
    'selectAll': 'Select All',
    'noParentsLinked': 'No parents linked',
    'selectTime': 'Select Time',
    'endTimeMustBeAfterStartTime': 'End time must be after start time',
    'pleaseEnterTitle': 'Please enter a title',
    'timeConflict': 'Time Conflict',
    'someInviteesAlreadyBooked':
        'Some invitees are already booked at this time.',
    'you': 'You',
    'noEmployeesSelected': 'No employees selected',
    'employeeSelected': 'employee selected',
    'employeesSelected': 'employees selected',
    'noParentsInvited': 'No parents invited',
    'parentInvited': 'parent invited',
    'parentsInvited': 'parents invited',
    'createAppointment': 'Create Appointment',
    'create': 'Create',
    'tasks': 'Tasks',
    'submit': 'Submit',
    'upload': 'Upload',
    'openChat': 'Open Chat',
    'score': 'Score',
    'progress': 'Progress',
    'description': 'Description',
    'attachments': 'Attachments',
    'taskDetail': 'Task Detail',
    'moreOptionsComingSoon': 'More options coming soon',
    'assignedBy': 'Assigned by',
    'notGraded': 'Not graded',
    'practiceTarget': 'Practice Target',
    'yourProgress': 'Your Progress',
    'submissionPlanRounds': 'Submission plan · {count} rounds',
    'checkpointsSubmitted': '{submitted} of {total} checkpoints submitted',
    'lateSubmitted': 'Late Submitted',
    'earlySubmitted': 'Early Submitted',
    'missed': 'Missed',
    'waitingToSubmit': 'Waiting to submit',
    'pointsSuffix': 'pts',
    'waitingForThisCheckpoint': 'Waiting for this checkpoint',
    'sentDate': 'Sent {date}',
    'reviewedDate': 'Reviewed {date}',
    'notStarted': 'Not Started',
    'teacherMarkedTaskComplete':
        'Your teacher has marked this task as complete.',
    'teacherProgressMessage':
        "Your teacher says you're {progress}% of the way through this task.",
    'teacherNoProgressYet':
        "Your teacher hasn't recorded any progress on this task yet.",
    'noDescriptionProvided': 'No description provided.',
    'noAttachments': 'No attachments',
    'filesCount': '{count} files',
    'teacherHasNotAddedFiles': "The teacher hasn't added any files yet.",
    'tapToViewAllAttachments': 'Tap to view all attachments',
    'toSubmit': 'To Submit',
    'photoOfCompletedWork': 'Photo of your completed work',
    'uploadClearPhotosOrPdf': 'Upload clear photos or a PDF file.',
    'couldNotOpenNamedFile': 'Could not open {name}',
    'submissionRoundLocked':
        'This submission round is locked. Choose an open round.',
    'missingStudent': 'Missing student',
    'noStudentSelectedForTask': 'No student is selected for this task.',
    'uploading': 'Uploading...',
    'uploaded': 'Uploaded',
    'fileSubmittedSuccessfully': '{name} was submitted successfully.',
    'fileSubmittedForCheckpoint':
        '{name} was submitted for checkpoint {index}.',
    'uploadFailed': 'Upload failed',
    'fromTeacherCount': 'From Teacher ({count})',
    'fromYouCount': 'From You ({count})',
    'filesFromTeacher': 'Files from Teacher',
    'teacherHasNotUploadedFiles':
        "The teacher hasn't uploaded any files for this task yet.",
    'yourSubmittedFiles': 'Your Submitted Files',
    'youHaveNotSubmittedFiles':
        "You haven't submitted any files for this task yet.",
    'submissionPlan': 'Submission plan',
    'nextCheckpointSelectedAutomatically':
        'Your next available checkpoint is selected automatically.',
    'submitYourWork': 'Submit Your Work',
    'uploadYourWorkHere': 'Upload your work here',
    'photosPdfOrOtherFiles': 'Photos, PDF, or other files',
    'chooseFile': 'Choose File',
    'readyToUpload': 'Ready to upload',
    'pdfFile': 'PDF file',
    'image': 'Image',
    'video': 'Video',
    'document': 'Document',
    'file': 'File',
    'chooseFromGallery': 'Choose from gallery',
    'choosePdfDocFile': 'Choose a file (PDF, DOC)',
    'documents': 'Documents',
    'previewSupportsImagesPdf': 'Preview supports images and PDF files.',
    'closePreview': 'Close preview',
    'taskChat': 'Task Chat',
    'notSignedIn': 'Not signed in',
    'signInAgainToSendMessages': 'Please sign in again to send messages.',
    'messageNotSent': 'Message not sent',
    'checkConnectionTryAgain': 'Please check your connection and try again.',
    'reactionFailedTryAgain': 'Reaction failed. Please try again.',
    'originalMessageNotFound': 'Original message not found.',
    'chatFiles': 'Chat files',
    'couldNotSelectFile': 'Could not select this file.',
    'attachmentNotSent': 'Attachment was not sent.',
    'microphonePermissionRequired': 'Microphone permission is required.',
    'replyingToMessage': 'Replying to {sender}: {message}',
    'typeMessage': 'Type a message...',
    'couldNotLoadMessages': "Couldn't load messages",
    'noMessagesYet': 'No messages yet',
    'sendMessageStartTeacherConversation':
        'Send a message to start the conversation with the teacher.',
    'reply': 'Reply',
    'deleteMessage': 'Delete message',
    'react': 'React',
    'attachment': 'Attachment',
    'assigned': 'Assigned',
    'inProgress': 'In Progress',
    'completed': 'Completed',
    'couldNotLoadTasks': 'Could not load tasks',
    'chooseStudentTasksHint':
        'Choose a student from the home screen to view their tasks.',
    'couldNotLoadTimetable': 'Could not load timetable.',
    'noClassesScheduledForThisDay': 'No classes scheduled for this day.',
    'classTimetable': 'Class timetable',
    'minutesShort': '{count} min',
    'filterComingSoon': 'Filter coming soon',
    'calendarComingSoon': 'Calendar coming soon',
    'taskHistoryComingSoon': 'Task history coming soon',
    'searchTasksHint': 'Search tasks...',
    'nothingHereYet': 'Nothing here yet',
    'assignedTasksEmptyHint': 'Tasks assigned to your child will show up here.',
    'upcomingTasks': 'Upcoming Tasks',
    'newLabel': 'New',
    'daysLeftOne': '{count} day left',
    'daysLeftMany': '{count} days left',
    'noDueDate': 'No due date',
    'keepTrackDueDates': 'Keep track of due dates!',
    'submitWorkOnTime': 'Submit your work on time and stay up to date.',
    'viewCalendar': 'View Calendar',
    'noCompletedTasksYet': 'No completed tasks yet.',
    'tasksCompleted': '{count} {task} completed.',
    'taskSingular': 'task',
    'taskPlural': 'tasks',
    'seeFullHistory': 'See full history ->',
    'homework': 'Homework',
    'overview': 'Overview',
    'homeworkProgress': 'Homework Progress',
    'homeworkList': 'Homework List',
    'itemSingular': 'item',
    'itemPlural': 'items',
    'overdue': 'Overdue',
    'searchHomeworkHint': 'Search subject / grade / teacher...',
    'due': 'Due',
    'latest': 'Latest',
    'nearestDue': 'Nearest due',
    'latestDue': 'Latest due',
    'subjectAZ': 'Subject A-Z',
    'grade': 'Grade',
    'total': 'Total',
    'received': 'Received',
    'dueDate': 'Due Date',
    'viewHomeworkDetails': 'View homework details',
    'submitHomework': 'Submit homework',
    'homeworkDetail': 'Homework Detail',
    'homeworkSubmitted': 'Homework submitted',
    'submissionClosed': 'Submission closed',
    'questions': 'Questions',
    'tasksInThisHomework': 'Tasks in this homework',
    'couldNotOpenFile': 'Could not open file',
    'reviewSubmission': 'Review submission',
    'homeworkSubmittedSuccessfully': 'Homework was submitted successfully.',
    'submissionFailed': 'Submission failed',
    'confirmSubmission': 'Confirm submission',
    'scoreBreakdown': 'Score breakdown',
    'questionShort': 'Q{index}',
    'teacherFeedback': 'Teacher feedback',
    'chooseAttachWork': 'Choose how you want to attach your work.',
    'takePhoto': 'Take a photo',
    'uploadFromPhone': 'Upload from phone',
    'totalScore': 'Total score',
    'instruction': 'Instruction',
    'points': '{score} pts',
    'scoreOutOfPoints': '{score} / {total} pts',
    'save': 'Save',
    'savingImage': 'Saving image...',
    'imageSaved': 'Image saved',
    'homeworkImageSavedToGallery':
        'The homework image was saved to your gallery.',
    'homeworkImageSavedSuccessfully':
        'The homework image was saved successfully.',
    'couldNotSaveImage': 'Could not save image',
    'couldNotDownloadImage': 'Could not download image ({statusCode}).',
    'imageCouldNotBeSaved': 'The image could not be saved.',
    'images': 'Images',
    'yourScore': 'Your Score',
    'nothingHere': 'Nothing here',
    'noHomeworkMatchesFilter': 'No homework matches the current filter.',
    'couldNotLoadHomework': "Couldn't load homework",
    'noStudentSelected': 'No student selected',
    'pickStudentHomeworkHint':
        "Pick a student from the home screen. We'll show only the homework assigned to their class.",
    'specialTasks': 'Special tasks',
    'reports': 'Reports',
    'notificationSenderAlphaSchool': 'Alpha School',
    'notificationSenderTeacherLina': 'Teacher - Ms. Lina',
    'notificationSenderFinanceOffice': 'Finance Office',
    'notificationSenderLibrary': 'Library',
    'notificationImportantTitle': 'Important announcement',
    'notificationParentMeetingBody':
        'See you at the parent meeting on Friday at 15:00.',
    'notificationHomeworkTitle': 'Homework',
    'notificationMathHomeworkBody': 'Submit math homework before 18:00.',
    'notificationTuitionReminderTitle': 'Tuition reminder',
    'notificationTuitionReminderBody': 'Please pay tuition before the 28th.',
    'notificationReturnBookTitle': 'Return book',
    'notificationReturnBookBody': 'The borrowed book is due in 2 days.',
    'selectMonth': 'Select month',
    'classroomLabel': 'Class',
    'studentIdLabel': 'ID',
    'allMonths': 'All months',
    'trackStudentAttendance': 'Track student attendance',
    'attended': 'Attended',
    'absent': 'Absent',
    'daysCountLabel': 'Day(s)',
    'date': 'Date',
    'reason': 'Reason',
    'attendanceNote': 'Note',
    'status': 'Status',
    'noAttendanceRecords': 'No attendance records',
    'late': 'Late',
    'normal': 'Normal',
    'checkIn': 'Check-in',
    'attendancePresent': 'Present',
    'attendanceEarly': 'Early',
    'arrivedEarly': 'Arrived early',
    'onTime': 'On time',
    'arrivedLate': 'Arrived late',
    'recorded': 'Recorded',
    'scannedViaQrCode': 'Scanned via QR code',
    'alreadyCheckedIn': 'Already checked in',
    'checkedInAt': 'Checked in at',
    'qrCodeAlreadyScannedToday': 'This QR code has already been scanned today.',
    'scanNextStudent': 'Scan Next Student',
    'checkInFailed': 'Check-in Failed',
    'attendanceRuleNotFound': 'Attendance rule not found',
    'scanHistory': 'Scan History',
    'scannedStudents': 'Scanned',
    'noScanRecords': 'No scan records for this day.',
    'pleaseSelectStudentFirst': 'Please select a student first.',
    'loading': 'Loading...',
    'participation': 'Participation',
    'dailyActivityScores': 'Daily activity scores',
    'activityWeights': 'Activity Weights',
    'selectedDay': 'Selected day',
    'noActivitiesToday': 'No activities today',
    'noActivitiesOnThisDay': 'No activities on this day',
    'tryDifferentDayFromCalendar':
        'Try picking a different day from the calendar.',
    'backToToday': 'Back to today',
    'selectAStudent': 'Select a student',
    'pickStudentParticipationScores':
        'Pick a student from the home screen to view their participation scores.',
    'activityCountOne': '{count} activity',
    'activityCountMany': '{count} activities',
    'couldNotLoadScores': "Couldn't load scores",
    'weekdayMonShort': 'Mon',
    'weekdayTueShort': 'Tue',
    'weekdayWedShort': 'Wed',
    'weekdayThuShort': 'Thu',
    'weekdayFriShort': 'Fri',
    'weekdaySatShort': 'Sat',
    'weekdaySunShort': 'Sun',
    'monthJanShort': 'Jan',
    'monthFebShort': 'Feb',
    'monthMarShort': 'Mar',
    'monthAprShort': 'Apr',
    'monthMayShort': 'May',
    'monthJunShort': 'Jun',
    'monthJulShort': 'Jul',
    'monthAugShort': 'Aug',
    'monthSepShort': 'Sep',
    'monthOctShort': 'Oct',
    'monthNovShort': 'Nov',
    'monthDecShort': 'Dec',
    'yearCalendar': 'Year Calendar',
    'eventsToday': 'Events Today',
    'noEvents': 'No events',
    'previewOnlyHint': 'This screen is preview-only.',
    'preview': 'Preview',
    'eventCountOne': '{count} event',
    'eventCountMany': '{count} events',
    'pickMonth': 'Pick Month',
    'eventsOn': 'Events on',
    'tapDayAboveHint': 'Tap a day above to see events.',
    'selected': 'Selected',
    'type': 'Type',
    'title': 'Title',
    'event': 'Event',
    'task': 'Task',
    'holiday': 'Holiday',
    'weekdayMonTiny': 'M',
    'weekdayTueTiny': 'T',
    'weekdayWedTiny': 'W',
    'weekdayThuTiny': 'T',
    'weekdayFriTiny': 'F',
    'weekdaySatTiny': 'S',
    'weekdaySunTiny': 'S',
    'weekdayMonCalendar': 'Mon',
    'weekdayTueCalendar': 'Tue',
    'weekdayWedCalendar': 'Wed',
    'weekdayThuCalendar': 'Thu',
    'weekdayFriCalendar': 'Fri',
    'weekdaySatCalendar': 'Sat',
    'weekdaySunCalendar': 'Sun',
    'demoCalendarParentMeeting': 'Parent Meeting',
    'demoCalendarParentMeetingNote': 'Room 2A • 09:00',
    'demoCalendarDesignReview': 'Design Review',
    'demoCalendarDesignReviewNote': 'Banner drafts',
    'demoCalendarSportsDay': 'Sports Day',
    'demoCalendarSportsDayNote': 'Bring sports uniform',
    'demoCalendarHoliday': 'Holiday',
    'demoCalendarHolidayNote': 'School closed',
    'demoCalendarVaccinationCheck': 'Vaccination Check',
    'demoCalendarVaccinationCheckNote': 'Bring health book',
    'demoCalendarSystemMaintenance': 'System Maintenance',
    'demoCalendarSystemMaintenanceNote': 'Firebase deploy',
    'demoCalendarNewTermBegins': 'New Term Begins',
    'demoCalendarNewTermBeginsNote': 'Welcome back!',
    'demoCalendarYearEndCelebration': 'Year-End Celebration',
    'demoCalendarYearEndCelebrationNote': 'Auditorium • 15:00',
    'demoCalendarDecorationSetup': 'Decoration Setup',
    'demoCalendarDecorationSetupNote': 'Front Office',
  };

  static const Map<String, String> _laFallbacks = {
    'studentsCardViewCount': 'ມຸມມອງບັດ • ນັກຮຽນ {count} ຄົນ',
    'noStudentsYet': 'ຍັງບໍ່ມີນັກຮຽນ',
    'addChildToGetStarted': 'ເພີ່ມຂໍ້ມູນລູກຂອງທ່ານເພື່ອເລີ່ມຕົ້ນ.',
    'emptyStudentsTip':
        'ຄຳແນະນຳ: ແຕະ “ເພີ່ມນັກຮຽນ” ດ້ານລຸ່ມ ແລະ ກອກຂໍ້ມູນລູກຂອງທ່ານເພື່ອເຊື່ອມກັບບັນຊີ. ຫຼັງຈາກສົ່ງແລ້ວ ຜູ້ດູແລຈະກວດສອບ ແລະ ອະນຸມັດ.',
    'addStudent': 'ເພີ່ມນັກຮຽນ',
    'addAStudent': 'ເພີ່ມນັກຮຽນ',
    'submitStudentApplicationHint': 'ສົ່ງຄຳຮ້ອງໃໝ່ — ຜູ້ດູແລຈະກວດສອບ.',
    'student': 'ນັກຮຽນ',
    'studentInformationTitle': 'ຂໍ້ມູນນັກຮຽນ',
    'studentInformationSubtitle':
        'ກະລຸນາກອກຂໍ້ມູນລູກຂອງທ່ານ. ຊ່ອງທີ່ມີ * ແມ່ນຈຳເປັນ.',
    'studentStepOf': 'ຂັ້ນຕອນ {step} ຈາກ 6',
    'branch': 'ສາຂາ',
    'selectBranch': 'ເລືອກສາຂາ',
    'loadingBranches': 'ກຳລັງໂຫຼດສາຂາ...',
    'education': 'ການສຶກສາ',
    'sibling': 'ພີ່ນ້ອງ',
    'liveWith': 'ອາໄສຢູ່ກັບ',
    'emergency': 'ສຸກເສີນ',
    'skip': 'ຂ້າມ',
    'submitApplication': 'ສົ່ງຄຳຮ້ອງ',
    'selectPlaceholder': 'ເລືອກ...',
    'useSavedDetails': 'ໃຊ້ຂໍ້ມູນທີ່ບັນທຶກໄວ້',
    'useSavedDetailsSubtitle':
        'ຕື່ມທີ່ຢູ່ຄົວເຮືອນ, ຜູ້ອາໄສຢູ່ນຳ ແລະ ຜູ້ຕິດຕໍ່ສຸກເສີນ.',
    'use': 'ໃຊ້',
    'studentHealth': 'ສຸຂະພາບນັກຮຽນ',
    'studentHealthOptionHint': 'ເລືອກຕົວເລືອກນີ້ສະເພາະເມື່ອກ່ຽວຂ້ອງກັບນັກຮຽນ.',
    'physicalMobilityDisabilities': 'ຄວາມພິການທາງຮ່າງກາຍ ແລະ ການເຄື່ອນໄຫວ',
    'sensoryDisabilities': 'ຄວາມພິການທາງປະສາດສຳຜັດ',
    'intellectualCognitiveDisabilities': 'ຄວາມພິການທາງສະຕິປັນຍາ ແລະ ການຮັບຮູ້',
    'neurodevelopmentalLearningDisabilities':
        'ຄວາມພິການດ້ານພັດທະນາການປະສາດ ແລະ ການຮຽນຮູ້',
    'psychiatricMentalHealthDisabilities': 'ຄວາມພິການດ້ານຈິດໃຈ ແລະ ສຸຂະພາບຈິດ',
    'chronicInvisibleDisabilities':
        'ພະຍາດຊໍາເຮື້ອ ແລະ ຄວາມພິການທີ່ເບິ່ງບໍ່ເຫັນ',
    'placeOfBirth': 'ສະຖານທີ່ເກີດ',
    'villageOfBirth': 'ບ້ານເກີດ',
    'provinceOfBirth': 'ແຂວງເກີດ',
    'districtOfBirth': 'ເມືອງເກີດ',
    'currentAddress': 'ທີ່ຢູ່ປັດຈຸບັນ',
    'educationHistoryKindergarten': 'ປະຫວັດການຮຽນ — ອະນຸບານ',
    'primaryHistory': 'ປະຫວັດການຮຽນຊັ້ນປະຖົມ',
    'yearLevel': 'ປີ / ຊັ້ນຮຽນ',
    'school': 'ໂຮງຮຽນ',
    'enterSchoolName': 'ປ້ອນຊື່ໂຮງຮຽນ',
    'addSibling': 'ເພີ່ມພີ່ນ້ອງ',
    'addAnotherSibling': 'ເພີ່ມພີ່ນ້ອງອີກຄົນ',
    'noSiblingsAddedYet': 'ຍັງບໍ່ມີພີ່ນ້ອງ',
    'siblingsEmptyHint':
        'ເພີ່ມອ້າຍ, ເອື້ອຍ, ນ້ອງ ທີ່ເປັນພີ່ນ້ອງໂດຍກົງຂອງນັກຮຽນ ຫຼື ຂ້າມຂັ້ນຕອນນີ້.',
    'siblingUpper': 'ພີ່ນ້ອງ',
    'fullName': 'ຊື່ເຕັມ',
    'enterFullName': 'ປ້ອນຊື່ເຕັມ',
    'currentSchoolName': 'ຊື່ໂຮງຮຽນປັດຈຸບັນ',
    'enterCurrentSchool': 'ປ້ອນໂຮງຮຽນປັດຈຸບັນ',
    'enterPhone1': 'ປ້ອນເບີໂທ 1',
    'enterPhone2': 'ປ້ອນເບີໂທ 2',
    'dateFormatPlaceholder': 'ວັນ/ເດືອນ/ປີ',
    'exampleAcademicYearKindergarten': 'ຕົວຢ່າງ 2019-2020',
    'exampleKindergartenLevel': 'ຕົວຢ່າງ ອະນຸບານ 1',
    'exampleAcademicYearPrimary': 'ຕົວຢ່າງ 2022-2023',
    'examplePrimaryLevel': 'ຕົວຢ່າງ ປ.1',
    'remove': 'ລຶບ',
    'addPersonLivingWithStudent': 'ເພີ່ມຜູ້ທີ່ອາໄສຢູ່ກັບນັກຮຽນ',
    'addAnotherPerson': 'ເພີ່ມອີກຄົນ',
    'onePersonRequired': 'ຕ້ອງເພີ່ມຢ່າງໜ້ອຍ 1 ຄົນ',
    'noOneAddedYet': 'ຍັງບໍ່ມີຜູ້ໃດຖືກເພີ່ມ',
    'livingWithEmptyHint': 'ເພີ່ມຢ່າງໜ້ອຍ 1 ຄົນທີ່ອາໄສຢູ່ກັບນັກຮຽນ.',
    'personLivingWithStudentUpper': 'ຜູ້ທີ່ອາໄສຢູ່ກັບນັກຮຽນ',
    'tapToExpand': 'ແຕະເພື່ອຂະຫຍາຍ',
    'selectLevel': 'ເລືອກລະດັບ',
    'occupation': 'ອາຊີບ',
    'enterOccupation': 'ປ້ອນອາຊີບ',
    'addEmergencyContact': 'ເພີ່ມຜູ້ຕິດຕໍ່ສຸກເສີນ',
    'addAnotherEmergencyContact': 'ເພີ່ມຜູ້ຕິດຕໍ່ສຸກເສີນອີກຄົນ',
    'oneEmergencyContactRequired': 'ຕ້ອງເພີ່ມຜູ້ຕິດຕໍ່ສຸກເສີນຢ່າງໜ້ອຍ 1 ຄົນ',
    'noEmergencyContactAddedYet': 'ຍັງບໍ່ມີຜູ້ຕິດຕໍ່ສຸກເສີນ',
    'emergencyEmptyHint':
        'ເພີ່ມຜູ້ຕິດຕໍ່ສຸກເສີນທີ່ໂຮງຮຽນສາມາດຕິດຕໍ່ໄດ້ເມື່ອຈຳເປັນ.',
    'emergencyContactUpper': 'ຜູ້ຕິດຕໍ່ສຸກເສີນ',
    'relationshipToStudent': 'ຄວາມສຳພັນກັບນັກຮຽນ',
    'enterRelationship': 'ປ້ອນຄວາມສຳພັນ',
    'hospital': 'ໂຮງໝໍ',
    'enterHospitalName': 'ປ້ອນຊື່ໂຮງໝໍ',
    'doctorName': 'ຊື່ທ່ານໝໍ',
    'enterDoctorName': 'ປ້ອນຊື່ທ່ານໝໍ',
    'doctorContact': 'ເບີຕິດຕໍ່ທ່ານໝໍ',
    'enterDoctorContact': 'ປ້ອນເບີຕິດຕໍ່ທ່ານໝໍ',
    'male': 'ຊາຍ',
    'female': 'ຍິງ',
    'other': 'ອື່ນໆ',
    'village': 'ບ້ານ',
    'province': 'ແຂວງ',
    'district': 'ເມືອງ',
    'enterVillage': 'ປ້ອນຊື່ບ້ານ',
    'loadingProvinces': 'ກຳລັງໂຫຼດແຂວງ...',
    'couldNotLoadProvinces': 'ບໍ່ສາມາດໂຫຼດແຂວງໄດ້',
    'selectProvince': 'ເລືອກແຂວງ',
    'selectProvinceFirst': 'ເລືອກແຂວງກ່ອນ',
    'selectDistrict': 'ເລືອກເມືອງ',
    'selectDistrictFirst': 'ເລືອກເມືອງກ່ອນ',
    'selectVillage': 'ເລືອກບ້ານ',
    'academicYear': 'ສົກຮຽນ',
    'temporaryPlatformNoticeButton': 'ແຈ້ງການໃຊ້ງານຊົ່ວຄາວ',
    'temporaryPlatformNoticeTitle': 'ແຈ້ງການໃຊ້ງານຊົ່ວຄາວ',
    'temporaryPlatformNoticeBody':
        'ເວັບນີ້ເປີດໃຫ້ໃຊ້ງານຊົ່ວຄາວ ເພື່ອໃຫ້ທ່ານເຂົ້າໃຊ້ລະບົບໂຮງຮຽນໄດ້ໃນຕອນນີ້. ຕໍ່ໄປໂຮງຮຽນຈະຍ້າຍໄປໃຊ້ Sivatthana Application ເປັນຊ່ອງທາງຫຼັກສຳລັບຂ່າວສານ ແລະ ບໍລິການຂອງໂຮງຮຽນ. ສາມາດດາວໂຫຼດແອັບໄດ້ຜ່ານ App Store ຫຼື Google Play ເມື່ອເປີດໃຫ້ດາວໂຫຼດ.',
    'temporaryPlatformNoticeStoreLabel': 'ຈະເປີດໃຫ້ດາວໂຫຼດຜ່ານ',
    'educationLevel': 'ລະດັບການສຶກສາ',
    'workplace': 'ສະຖານທີ່ເຮັດວຽກ',
    'enterWorkplace': 'ປ້ອນສະຖານທີ່ເຮັດວຽກ',
    'email': 'ອີເມວ',
    'enterEmail': 'ປ້ອນອີເມວ',
    'phoneNo1': 'ເບີໂທ 1',
    'phoneNo2': 'ເບີໂທ 2',
    'enterPhoneNumber': 'ປ້ອນເບີໂທ 020XXXXXXXX',
    'idCardNo': 'ເລກບັດປະຈຳຕົວ',
    'enterIdCardNumber': 'ປ້ອນເລກບັດປະຈຳຕົວ',
    'passportNo': 'ເລກໜັງສືຜ່ານແດນ',
    'enterPassportNumber': 'ປ້ອນເລກໜັງສືຜ່ານແດນ',
    'familyBookNo': 'ເລກສຳມະໂນຄົວ',
    'enterFamilyBookNumber': 'ປ້ອນເລກສຳມະໂນຄົວ',
    'identityCard': 'ຮູບບັດປະຈຳຕົວ',
    'familyBookUpload': 'ຮູບປຶ້ມສຳມະໂນຄົວ (PDF ຫຼື ຮູບ)',
    'nationality': 'ສັນຊາດ',
    'enterNationality': 'ປ້ອນສັນຊາດ',
    'ethnicity': 'ຊົນເຜົ່າ',
    'enterEthnicity': 'ປ້ອນຊົນເຜົ່າ',
    'religion': 'ສາສະໜາ',
    'enterReligion': 'ປ້ອນສາສະໜາ',
    'homeNo': 'ເລກເຮືອນ',
    'enterHomeNumber': 'ປ້ອນເລກເຮືອນ',
    'homeUnit': 'ໜ່ວຍເຮືອນ',
    'enterUnitRoom': 'ປ້ອນໜ່ວຍ / ຫ້ອງ',
    'mobilityDisability': 'ຄວາມພິການດ້ານການເຄື່ອນໄຫວ',
    'difficultyWalkingStairs': 'ຍາກໃນການຍ່າງ ຫຼື ຂຶ້ນລົງຂັ້ນໄດ',
    'requiresMobilityAids': 'ມັກຕ້ອງໃຊ້ລໍ້ນັ່ງ, ໄມ້ຄ້ຳ ຫຼື ໄມ້ເທົ້າ.',
    'amputationLimbDifferences': 'ການຂາດອະໄວຍະວະ ຫຼື ຄວາມແຕກຕ່າງຂອງແຂນຂາ',
    'neuromuscularConditions': 'ພາວະກ້າມເນື້ອ ແລະ ລະບົບປະສາດ',
    'missingLimbsDetail':
        'ຂາດແຂນຂາຕັ້ງແຕ່ເກີດ, ຈາກອຸບັດເຫດ ຫຼື ການຮັກສາທາງການແພດ.',
    'cerebralPalsy': 'ສະໝອງພິການ',
    'muscularDystrophy': 'ກ້າມເນື້ອເສື່ອມ',
    'multipleSclerosis': 'ໂຣກປະສາດເສື່ອມແຂງ',
    'spinalCordInjuries': 'ການບາດເຈັບໄຂສັນຫຼັງ',
    'partialSpinalTrauma': 'ບາດເຈັບກະດູກສັນຫຼັງທີ່ສົ່ງຜົນບາງສ່ວນ',
    'fullSpinalParalysis': 'ບາດເຈັບກະດູກສັນຫຼັງທີ່ສົ່ງຜົນໃຫ້ອຳມະພາດ',
    'visualDifferences': 'ຄວາມແຕກຕ່າງດ້ານການເບິ່ງເຫັນ',
    'lowVisionDetail': 'ສາຍຕາຕ່ຳທີ່ແວ່ນຕາບໍ່ສາມາດແກ້ໄດ້',
    'legalBlindness': 'ຕາບອດຕາມເກນທາງກົດໝາຍ',
    'totalBlindness': 'ຕາບອດສະໜິດ',
    'colourblindness': 'ຕາບອດສີ',
    'albinismAniridia': 'ພາວະຜິວເຜືອກ ຫຼື ບໍ່ມີມ່ານຕາ',
    'hearingLoss': 'ການສູນເສຍການໄດ້ຍິນ',
    'mildHearingLoss': 'ຫູຕຶງລະດັບເບົາ (ບໍ່ໄດ້ຍິນສຽງເບົາ)',
    'moderateHearingLoss': 'ຫູຕຶງລະດັບປານກາງ (ຟັງຄຳເວົ້າປົກກະຕິໄດ້ຍາກ)',
    'severeHearingLoss': 'ຫູຕຶງລະດັບຮຸນແຮງ (ບໍ່ໄດ້ຍິນຄຳເວົ້າ)',
    'profoundDeafness':
        'ຫູໜວກລະດັບຮຸນແຮງຫຼາຍ (ບໍ່ໄດ້ຍິນຄຳເວົ້າ ແລະ ຮັບຮູ້ໄດ້ແຕ່ສຽງດັງຫຼາຍ)',
    'sensoryProcessingDifferences': 'ຄວາມແຕກຕ່າງໃນການປະມວນຜົນປະສາດສຳຜັດ',
    'interoceptionDetail':
        'ການຮັບຮູ້ສັນຍານພາຍໃນຮ່າງກາຍ: ເຊັ່ນ ອັດຕາການເຕັ້ນຫົວໃຈ, ຄວາມຫິວ, ຄວາມກະຫາຍ ແລະ ຄວາມຕ້ອງການເຂົ້າຫ້ອງນ້ຳ.',
    'mildIntellectualDisability': 'ຄວາມພິການທາງສະຕິປັນຍາລະດັບເບົາ',
    'moderateIntellectualDisability': 'ຄວາມພິການທາງສະຕິປັນຍາລະດັບປານກາງ',
    'severeIntellectualDisability': 'ຄວາມພິການທາງສະຕິປັນຍາລະດັບຮຸນແຮງ',
    'traumaticBrainInjuries': 'ການບາດເຈັບສະໝອງ (TBI)',
    'hypoxicAnoxicBrainInjury': 'ສະໝອງບາດເຈັບຈາກຂາດອອກຊີເຈນ',
    'stroke': 'ອຳມະພາດຈາກຫຼອດເລືອດສະໝອງ',
    'specificLearningDisabilities': 'ຄວາມບົກພ່ອງດ້ານການຮຽນຮູ້ສະເພາະ',
    'specificLearningDescription': 'ມີຄວາມຍາກໃນທັກສະການຮຽນບາງດ້ານ ເຊັ່ນ',
    'dyslexiaReading': 'ອ່ານຍາກ',
    'dyscalculiaMath': 'ຄິດໄລ່ຍາກ',
    'dysgraphiaWriting': 'ຂຽນຍາກ',
    'autismSpectrumDisorder': 'ພາວະອອທິສຕິກ (ASD)',
    'adhd': 'ADHD',
    'foetalAlcoholSpectrumDisorders': 'ກຸ່ມອາການຈາກແອລກໍຮໍໃນຄັນ',
    'developmentalLanguageDisorder': 'ພາວະພັດທະນາການພາສາຜິດປົກກະຕິ',
    'moodDisorders': 'ຄວາມຜິດປົກກະຕິດ້ານອາລົມ',
    'majorDepressiveDisorder': 'ພາວະຊຶມເສົ້າຮຸນແຮງ',
    'bipolarDisorder': 'ໄບໂພລາ',
    'anxietyDisorders': 'ຄວາມຜິດປົກກະຕິດ້ານຄວາມກັງວົນ',
    'severeAnxiety': 'ຄວາມກັງວົນຮຸນແຮງ',
    'panicDisorder': 'ພາວະຕື່ນຕົກໃຈ',
    'obsessiveCompulsiveDisorder': 'ພາວະຍ້ຳຄິດຍ້ຳທຳ (OCD)',
    'postTraumaticStressDisorder': 'ພາວະເຄັດຫຼັງເຫດການຮ້າຍແຮງ (PTSD)',
    'respiratoryCardiovascularConditions': 'ພາວະລະບົບຫາຍໃຈ ແລະ ຫົວໃຈຫຼອດເລືອດ',
    'severe': 'ຮຸນແຮງ',
    'asthma': 'ຫອບຫືດ',
    'chooseAddStudentMethod': 'ເລືອກວິທີເພີ່ມລູກຂອງທ່ານ.',
    'fillInForm': 'ກອກແບບຟອມ',
    'fillInFormSubtitle': 'ກອກຂໍ້ມູນລູກຂອງທ່ານດ້ວຍຕົນເອງ.',
    'scanQrCode': 'ສະແກນ QR Code',
    'scanQrCodeSubtitle': 'ເພີ່ມນັກຮຽນໂດຍໃຊ້ QR Code ຈາກໂຮງຮຽນ.',
    'cameraError': 'ກ້ອງມີບັນຫາ: {error}',
    'cameraNeedsHttpsWeb':
        'ກ້ອງໃນເວັບຕ້ອງໃຊ້ HTTPS. ກະລຸນາເປີດ UAT ທີ່ https://app.classroomconnect.la/alpha-app-uat/',
    'cameraPermissionDenied':
        'ຍັງບໍ່ໄດ້ອະນຸຍາດໃຊ້ກ້ອງ. ກະລຸນາເປີດສິດໃຊ້ກ້ອງ ແລ້ວລອງໃໝ່.',
    'cameraScannerUnsupported':
        'ບຣາວເຊີ ຫຼື ອຸປະກອນນີ້ບໍ່ຮອງຮັບການສະແກນດ້ວຍກ້ອງ.',
    'invalidStudentQrCode': 'QR Code ນີ້ບໍ່ແມ່ນ QR Code ນັກຮຽນທີ່ຖືກຕ້ອງ.',
    'sessionMissingSignInAgain':
        'ບໍ່ພົບຂໍ້ມູນການເຂົ້າລະບົບ. ກະລຸນາເຂົ້າລະບົບໃໝ່.',
    'sessionMissingResubmit':
        'ບໍ່ພົບຂໍ້ມູນການເຂົ້າລະບົບ. ກະລຸນາເຂົ້າລະບົບໃໝ່ເພື່ອສົ່ງຄຳຮ້ອງອີກຄັ້ງ.',
    'sessionMissingAddStudent':
        'ບໍ່ພົບຂໍ້ມູນການເຂົ້າລະບົບ. ກະລຸນາເຂົ້າລະບົບໃໝ່ເພື່ອເພີ່ມນັກຮຽນ.',
    'unableToConnectTryAgain': 'ບໍ່ສາມາດເຊື່ອມຕໍ່ໄດ້. ກະລຸນາລອງໃໝ່.',
    'submittingRequest': 'ກຳລັງສົ່ງຄຳຮ້ອງ...',
    'processing': 'ກຳລັງດຳເນີນການ...',
    'alignStudentQrCodeFrame': 'ວາງ QR Code ຂອງນັກຮຽນໃຫ້ຢູ່ໃນກອບ',
    'scannerReadsAutomatically': 'ລະບົບຈະສະແກນອັດຕະໂນມັດເມື່ອກວດພົບ.',
    'attendanceQrCheckIn': 'ເຊັກຊື່ • ສະແກນ QR',
    'askOtherGuardianQrProfile':
        'ໃຫ້ຜູ້ປົກຄອງອີກຄົນເປີດ QR Code ຈາກໜ້າໂປຣໄຟລ໌.',
    'addStudentQrLinkRequest': 'ເພີ່ມນັກຮຽນ • ຄຳຮ້ອງເຊື່ອມ QR',
    'cantSendRequest': 'ບໍ່ສາມາດສົ່ງຄຳຮ້ອງນີ້ໄດ້',
    'scanAgain': 'ສະແກນອີກຄັ້ງ',
    'studentLinkedToAccount': 'ເຊື່ອມ {name} ເຂົ້າກັບບັນຊີຂອງທ່ານແລ້ວ.',
    'studentPendingAdminApproval': 'ນັກຮຽນຄົນນີ້ກຳລັງລໍຖ້າຜູ້ດູແລອະນຸມັດ.',
    'studentApprovedMessage': 'ອະນຸມັດ {name} ແລ້ວ.',
    'applicationDeleted': 'ລຶບຄຳຮ້ອງແລ້ວ.',
    'couldNotOpenResubmitStudentMissing':
        'ບໍ່ສາມາດເປີດແບບຟອມສົ່ງໃໝ່ໄດ້. ບໍ່ພົບລະຫັດນັກຮຽນ.',
    'addAnotherStudent': 'ເພີ່ມນັກຮຽນອີກຄົນ',
    'comingSoon': 'ຈະເປີດໃຊ້ໃນໄວໆນີ້',
    'somethingWentWrong': 'ມີບາງຢ່າງຜິດພາດ',
    'tryAgain': 'ລອງໃໝ່',
    'requestSent': 'ສົ່ງຄຳຮ້ອງແລ້ວ',
    'qrLinkRequestReviewMessage':
        'ຜູ້ດູແລຈະກວດສອບຄຳຮ້ອງຂອງທ່ານ. ຫຼັງຈາກອະນຸມັດແລ້ວ ນັກຮຽນຄົນນີ້ຈະສະແດງໃນບັນຊີຂອງທ່ານ.',
    'done': 'ສຳເລັດ',
    'pendingApproval': 'ລໍຖ້າອະນຸມັດ',
    'pendingApprovalUpper': 'ລໍຖ້າອະນຸມັດ',
    'studentSubmitted': 'ສົ່ງຂໍ້ມູນນັກຮຽນແລ້ວ',
    'linkRequestSubmitted': 'ສົ່ງຄຳຮ້ອງເຊື່ອມແລ້ວ',
    'studentRejectedTitle': 'ນັກຮຽນຖືກປະຕິເສດ',
    'linkRequestRejectedTitle': 'ຄຳຮ້ອງເຊື່ອມຖືກປະຕິເສດ',
    'thankYouNamePrefix': 'ຂອບໃຈ, ',
    'studentSubmittedMessage':
        '. ຄຳຮ້ອງຂອງທ່ານຖືກຮັບແລ້ວ ແລະ ກຳລັງລໍຖ້າຜູ້ດູແລອະນຸມັດ.',
    'linkRequestSubmittedMessage':
        '. ຄຳຮ້ອງເຊື່ອມນັກຮຽນຄົນນີ້ກຳລັງລໍຖ້າຜູ້ດູແລອະນຸມັດ.',
    'studentRejectedMessage': '. ຜູ້ດູແລໄດ້ກວດສອບຄຳຮ້ອງນີ້ ແລະ ຂໍໃຫ້ແກ້ໄຂ.',
    'linkRequestRejectedMessage':
        '. ຜູ້ດູແລໄດ້ກວດສອບຄຳຮ້ອງເຊື່ອມນີ້ ແລະ ປະຕິເສດ.',
    'qrLinkRequestReceived': 'ໄດ້ຮັບຄຳຮ້ອງເຊື່ອມ QR ແລ້ວ',
    'adminRejectedRequest': 'ຜູ້ດູແລປະຕິເສດຄຳຮ້ອງ',
    'closed': 'ປິດແລ້ວ',
    'studentWillAppearAfterApproval': 'ນັກຮຽນຈະສະແດງຫຼັງຈາກອະນຸມັດ',
    'backToStudents': 'ກັບໄປໜ້ານັກຮຽນ',
    'parentApplicationSubmittedTitle': 'ສົ່ງຄຳຮ້ອງສຳເລັດ',
    'parentApplicationSubmittedAlertTitle': 'ສົ່ງຄຳຮ້ອງສຳເລັດ',
    'parentApplicationSubmittedAlertMessage':
        'ຂໍ້ມູນຜູ້ປົກຄອງຂອງທ່ານຖືກສົ່ງແລ້ວ. ກະລຸນາລໍຖ້າຜູ້ດູແລອະນຸມັດກ່ອນເຂົ້າລະບົບ.',
    'parentApplicationApprovedAlertTitle': 'ຄຳຮ້ອງອະນຸມັດແລ້ວ',
    'parentApplicationApprovedAlertMessage':
        'ຄຳຮ້ອງຂອງທ່ານຖືກອະນຸມັດແລ້ວ. ທ່ານສາມາດເຂົ້າລະບົບດ້ວຍອີເມວ ແລະ ລະຫັດຜ່ານ.',
    'parentApplicationRejectedAlertTitle': 'ຄຳຮ້ອງຖືກປະຕິເສດ',
    'parentApplicationRejectedDefaultMessage':
        'ຜູ້ດູແລປະຕິເສດຄຳຮ້ອງຜູ້ປົກຄອງຂອງທ່ານ. ກະລຸນາກວດສອບຂໍ້ມູນ ແລະ ສົ່ງອີກຄັ້ງ.',
    'submissionFailed': 'ສົ່ງຄຳຮ້ອງບໍ່ສຳເລັດ',
    'resubmittingApplication': 'ກຳລັງສົ່ງຄຳຮ້ອງໃໝ່...',
    'addingStudent': 'ກຳລັງເພີ່ມນັກຮຽນ...',
    'couldNotResolveParentId': 'ບໍ່ສາມາດອ່ານເລກອ້າງອີງຜູ້ປົກຄອງຈາກຄຳຕອບໄດ້.',
    'studentRejectedAlertTitle': 'ນັກຮຽນຖືກປະຕິເສດ',
    'linkRequestRejectedAlertTitle': 'ຄຳຮ້ອງເຊື່ອມຖືກປະຕິເສດ',
    'studentRejectedDefaultMessage':
        'ຜູ້ດູແລປະຕິເສດ {name}. ກະລຸນາກວດສອບຂໍ້ມູນນັກຮຽນ ແລະ ສົ່ງອີກຄັ້ງ.',
    'linkRequestRejectedDefaultMessage':
        'ຜູ້ດູແລປະຕິເສດຄຳຮ້ອງເຊື່ອມ {name} ເຂົ້າກັບບັນຊີຂອງທ່ານ.',
    'reviewStudentInformationAndSubmitAgain':
        'ກະລຸນາກວດສອບຂໍ້ມູນນັກຮຽນ ແລະ ສົ່ງອີກຄັ້ງ.',
    'submitPreviousStudentApplicationFirst':
        'ກະລຸນາສົ່ງຄຳຮ້ອງນັກຮຽນກ່ອນໜ້ານີ້ກ່ອນ ເພື່ອບັນທຶກຂໍ້ມູນຄົວເຮືອນ.',
    'savedStudentDetailsAppliedMessage':
        'ຂໍ້ມູນທີ່ຢູ່ຄົວເຮືອນ, ຜູ້ອາໄສຢູ່ນຳ ແລະ ຜູ້ຕິດຕໍ່ສຸກເສີນຖືກຕື່ມໃຫ້ແລ້ວ.',
    'possibleDuplicate': 'ອາດຈະຊ້ຳກັນ',
    'possibleDuplicateMessage':
        'ນັກຮຽນຊື່ {names} ຖືກລົງທະບຽນໃນບັນຊີນີ້ແລ້ວ. ຕ້ອງການເພີ່ມນັກຮຽນຄົນນີ້ອີກບໍ?',
    'addAnyway': 'ເພີ່ມຕໍ່ໄປ',
    'preparingApplication': 'ກຳລັງກຽມຄຳຮ້ອງ...',
    'convertingFamilyBookSingle': 'ກຳລັງແປງຮູບສຳມະໂນຄົວເປັນ PDF...',
    'convertingFamilyBookMany': 'ກຳລັງແປງຮູບສຳມະໂນຄົວ {count} ຮູບເປັນ PDF...',
    'submittingApplication': 'ກຳລັງສົ່ງຄຳຮ້ອງ...',
    'couldNotResolveApplicationId': 'ບໍ່ສາມາດອ່ານເລກອ້າງອີງຄຳຮ້ອງໄດ້.',
    'noSavedDetailsYet': 'ຍັງບໍ່ມີຂໍ້ມູນທີ່ບັນທຶກ',
    'submitPreviousApplicationFirst':
        'ກະລຸນາສົ່ງຄຳຮ້ອງກ່ອນໜ້ານີ້ກ່ອນ ເພື່ອບັນທຶກຂໍ້ມູນຕິດຕໍ່ ເອກະສານ ແລະ ທີ່ຢູ່.',
    'savedDetailsApplied': 'ນຳໃຊ້ຂໍ້ມູນທີ່ບັນທຶກແລ້ວ',
    'savedParentDetailsAppliedMessage':
        'ຂໍ້ມູນຕິດຕໍ່ ເອກະສານ ແລະ ທີ່ຢູ່ທີ່ບັນທຶກໄວ້ຖືກຕື່ມໃຫ້ແລ້ວ. ຂັ້ນຕອນທີ 1 ເປັນຂໍ້ມູນສ່ວນຕົວ ແລະ ຕ້ອງກອກໃໝ່.',
    'fillSavedParentDetails':
        'ຕື່ມຂໍ້ມູນຕິດຕໍ່ ເອກະສານ ແລະ ທີ່ຢູ່ທີ່ບັນທຶກໄວ້.',
    'pleaseWait': 'ກະລຸນາລໍຖ້າ',
    'couldNotReadFile': 'ບໍ່ສາມາດອ່ານໄຟລ໌ນີ້ໄດ້',
    'pdf': 'PDF',
    'image': 'ຮູບພາບ',
    'choosePdfOrImages': 'ເລືອກ PDF ຫຼື ຮູບພາບ',
    'chooseEitherPdfOrImagesNotBoth':
        'ກະລຸນາເລືອກ PDF ຫຼື ຮູບພາບຢ່າງໃດຢ່າງໜຶ່ງ ບໍ່ໃຫ້ເລືອກປົນກັນ.',
    'chooseOnlyOnePdfFile': 'ກະລຸນາເລືອກໄຟລ໌ PDF ພຽງ 1 ໄຟລ໌.',
    'choosePdfJpgJpegPngFiles': 'ກະລຸນາເລືອກໄຟລ໌ PDF, JPG, JPEG ຫຼື PNG.',
    'choosePdf': 'ເລືອກ PDF',
    'chooseImage': 'ເລືອກຮູບພາບ',
    'tapToAddMore': 'ແຕະເພື່ອເພີ່ມອີກ',
    'convertedToPdf': '{name} -> PDF',
    'imagesConvertedToPdf': '{count} ຮູບ -> PDF',
    'reasonFromAdmin': 'ເຫດຜົນຈາກຜູ້ດູແລ',
    'parentApplicationThanks': 'ຂອບໃຈ',
    'parentApplicationWaitingMessage':
        'ຄຳຮ້ອງຂອງທ່ານຖືກຮັບແລ້ວ ແລະ ກຳລັງລໍຖ້າຜູ້ດູແລກວດສອບ.',
    'checkingStatus': 'ກຳລັງກວດສອບສະຖານະ...',
    'checkApprovalStatus': 'ກວດສອບສະຖານະອະນຸມັດ',
    'checkAgain': 'ກວດສອບອີກຄັ້ງ',
    'backToSignIn': 'ກັບໄປໜ້າເຂົ້າລະບົບ',
    'cancelApplication': 'ຍົກເລີກຄຳຮ້ອງ',
    'cancelApplicationQuestion': 'ຍົກເລີກຄຳຮ້ອງບໍ?',
    'cancelApplicationMessage':
        'ສະຖານະຄຳຮ້ອງທີ່ບັນທຶກໃນເຄື່ອງຈະຖືກລຶບ. ຂໍ້ມູນໃນລະບົບຈະຍັງຢູ່ຈົນກວ່າຜູ້ດູແລຈະລຶບອອກ.',
    'yourLogin': 'ຂໍ້ມູນເຂົ້າລະບົບ',
    'password': 'ລະຫັດຜ່ານ',
    'notAvailable': 'ບໍ່ມີຂໍ້ມູນ',
    'passwordUnavailable': 'ບໍ່ພົບລະຫັດຜ່ານ',
    'passwordUnavailableMessage':
        'ຄຳຮ້ອງນີ້ຖືກສົ່ງກ່ອນທີ່ຈະບັນທຶກລະຫັດຜ່ານໄວ້ໃນເຄື່ອງ. ກະລຸນາຍົກເລີກຄຳຮ້ອງ ແລະ ສົ່ງໃໝ່ເພື່ອເບິ່ງລະຫັດຜ່ານ.',
    'savePasswordHint':
        'ກະລຸນາບັນທຶກລະຫັດຜ່ານນີ້ໄວ້. ທ່ານສາມາດປ່ຽນໄດ້ຫຼັງຈາກຜູ້ດູແລອະນຸມັດບັນຊີ.',
    'hide': 'ເຊື່ອງ',
    'show': 'ສະແດງ',
    'submitted': 'ສົ່ງແລ້ວ',
    'applicationReceived': 'ໄດ້ຮັບຄຳຮ້ອງແລ້ວ',
    'pendingReview': 'ລໍຖ້າກວດສອບ',
    'adminRequestedChanges': 'ຜູ້ດູແລຂໍໃຫ້ແກ້ໄຂຂໍ້ມູນ',
    'waitingForAdminApproval': 'ລໍຖ້າຜູ້ດູແລອະນຸມັດ',
    'approved': 'ອະນຸມັດແລ້ວ',
    'accountApprovedUpper': 'ບັນຊີອະນຸມັດແລ້ວ',
    'youreApproved': 'ບັນຊີຂອງທ່ານອະນຸມັດແລ້ວ!',
    'welcome': 'ຍິນດີຕ້ອນຮັບ',
    'accountApprovedMessage':
        'ບັນຊີຂອງທ່ານເປີດໃຊ້ງານແລ້ວ. ທ່ານສາມາດເຂົ້າລະບົບໄດ້ທຸກເວລາດ້ວຍອີເມວ ແລະ ລະຫັດຜ່ານທີ່ສົ່ງໄວ້.',
    'goToSignIn': 'ໄປໜ້າເຂົ້າລະບົບ',
    'resubmit': 'ສົ່ງໃໝ່',
    'updateDetailsAndSendAgain': 'ແກ້ໄຂຂໍ້ມູນ ແລະ ສົ່ງໃໝ່',
    'editAndResubmit': 'ແກ້ໄຂ ແລະ ສົ່ງໃໝ່',
    'notifiedOnceApproved': 'ຈະແຈ້ງໃຫ້ທ່ານຮູ້ເມື່ອອະນຸມັດແລ້ວ',
    'qrLinkPending': 'ລໍຖ້າເຊື່ອມ QR',
    'rejected': 'ຖືກປະຕິເສດ',
    'rejectedUpper': 'ຖືກປະຕິເສດ',
    'applicationRejected': 'ຄຳຮ້ອງຖືກປະຕິເສດ',
    'applicationRejectedMessage': 'ຜູ້ດູແລໄດ້ກວດສອບຄຳຮ້ອງນີ້ ແລະ ຂໍໃຫ້ແກ້ໄຂ.',
    'reviewParentInformationAndSubmitAgain':
        'ກະລຸນາກວດສອບຂໍ້ມູນຜູ້ປົກຄອງ ແລະ ສົ່ງອີກຄັ້ງ.',
    'logout': 'ອອກຈາກລະບົບ',
    'logoutConfirmMessage': 'ທ່ານຕ້ອງການອອກຈາກລະບົບ ແລະ ກັບໄປໜ້າເຂົ້າລະບົບບໍ?',
    'cancel': 'ຍົກເລີກ',
    'settings': 'ຕັ້ງຄ່າ',
    'account': 'ບັນຊີ',
    'emergencyContact': 'ຜູ້ຕິດຕໍ່ສຸກເສີນ',
    'addContact': 'ເພີ່ມຜູ້ຕິດຕໍ່',
    'editContact': 'ແກ້ໄຂຜູ້ຕິດຕໍ່',
    'saveChanges': 'ບັນທຶກການແກ້ໄຂ',
    'job': 'ອາຊີບ',
    'workingPlace': 'ສະຖານທີ່ເຮັດວຽກ',
    'doctor': 'ທ່ານໝໍ',
    'ok': 'ຕົກລົງ',
    'edit': 'ແກ້ໄຂ',
    'saved': 'ບັນທຶກແລ້ວ',
    'saveFailed': 'ບັນທຶກບໍ່ສຳເລັດ',
    'missingInformation': 'ຂໍ້ມູນບໍ່ຄົບ',
    'nameAndPhoneRequired': 'ຕ້ອງປ້ອນຊື່ ແລະ ເບີໂທ 1.',
    'couldNotLoadEmergencyContact': 'ບໍ່ສາມາດໂຫຼດຜູ້ຕິດຕໍ່ສຸກເສີນໄດ້.',
    'couldNotSaveEmergencyContact': 'ບໍ່ສາມາດບັນທຶກຜູ້ຕິດຕໍ່ສຸກເສີນໄດ້.',
    'couldNotSaveEmergencyContactTryAgain':
        'ບໍ່ສາມາດບັນທຶກຜູ້ຕິດຕໍ່ສຸກເສີນໄດ້. ກະລຸນາລອງໃໝ່.',
    'limitReached': 'ເຖິງຂີດຈຳກັດແລ້ວ',
    'maxEmergencyContactsOnly':
        'ທ່ານສາມາດເພີ່ມຜູ້ຕິດຕໍ່ສຸກເສີນໄດ້ສູງສຸດ 5 ຄົນເທົ່ານັ້ນ.',
    'emergencyContactAdded': 'ເພີ່ມຜູ້ຕິດຕໍ່ສຸກເສີນແລ້ວ.',
    'contactUpdated': 'ອັບເດດຜູ້ຕິດຕໍ່ແລ້ວ',
    'emergencyContactSaved': 'ບັນທຶກຂໍ້ມູນຜູ້ຕິດຕໍ່ສຸກເສີນແລ້ວ.',
    'deleteContactQuestion': 'ລຶບຜູ້ຕິດຕໍ່ບໍ?',
    'removeEmergencyContactMessage': 'ລຶບ {name} ອອກຈາກຜູ້ຕິດຕໍ່ສຸກເສີນ.',
    'contactDeleted': 'ລຶບຜູ້ຕິດຕໍ່ແລ້ວ',
    'contactRemovedMessage': 'ລຶບ {name} ແລ້ວ.',
    'priorityUpdated': 'ອັບເດດລຳດັບຄວາມສຳຄັນແລ້ວ.',
    'noEmergencyContactFound': 'ບໍ່ພົບຜູ້ຕິດຕໍ່ສຸກເສີນ.',
    'noAdditionalDetails': 'ບໍ່ມີລາຍລະອຽດເພີ່ມເຕີມ.',
    'moveHigherPriority': 'ຍ້າຍລຳດັບໃຫ້ສູງຂຶ້ນ',
    'moveLowerPriority': 'ຍ້າຍລຳດັບໃຫ້ຕ່ຳລົງ',
    'language': 'ພາສາ',
    'english': 'English',
    'lao': 'ລາວ',
    'profile': 'ໂປຣໄຟລ໌',
    'profileSettings': 'ຕັ້ງຄ່າໂປຣໄຟລ໌',
    'profileSettingsSubtitle': 'ອັບເດດ ແລະ ແກ້ໄຂໂປຣໄຟລ໌ຂອງທ່ານ',
    'privacy': 'ຄວາມເປັນສ່ວນຕົວ',
    'privacySubtitle': 'ປ່ຽນລະຫັດຜ່ານຂອງທ່ານ',
    'notificationsSubtitle': 'ປ່ຽນການຕັ້ງຄ່າແຈ້ງເຕືອນ',
    'generalUpper': 'ທົ່ວໄປ',
    'studentQrCode': 'QR Code ນັກຮຽນ',
    'saveQrCode': 'ບັນທຶກ QR Code',
    'saving': 'ກຳລັງບັນທຶກ...',
    'savingQrCode': 'ກຳລັງບັນທຶກ QR Code...',
    'qrCodeNotReady': 'QR Code ຍັງບໍ່ພ້ອມ.',
    'qrCodeCouldNotBeSaved': 'ບໍ່ສາມາດບັນທຶກ QR Code ໄດ້.',
    'qrCodeSaved': 'ບັນທຶກ QR Code ແລ້ວ',
    'qrCodeSavedToGallery': 'QR Code ຖືກບັນທຶກໄປທີ່ຄັງຮູບພາບແລ້ວ.',
    'qrCodeSavedSuccessfully': 'ບັນທຶກ QR Code ສຳເລັດແລ້ວ.',
    'couldNotSaveQrCode': 'ບໍ່ສາມາດບັນທຶກ QR Code',
    'error': 'ຜິດພາດ',
    'contactCountOne': '{count} ລາຍຊື່',
    'contactCountMany': '{count} ລາຍຊື່',
    'selectLanguage': 'ເລືອກພາສາ',
    'fieldRequiredError': 'ກະລຸນາປ້ອນຂໍ້ມູນໃນຊ່ອງນີ້',
    'validEmailError': 'ກະລຸນາປ້ອນອີເມວໃຫ້ຖືກຕ້ອງ',
    'passwordMinLengthError': 'ລະຫັດຜ່ານຕ້ອງມີຢ່າງໜ້ອຍ 6 ຕົວອັກສອນ',
    'passwordsDoNotMatchError': 'ລະຫັດຜ່ານບໍ່ກົງກັນ',
    'uploadDocumentError': 'ກະລຸນາອັບໂຫຼດເອກະສານນີ້',
    'contactSchool': 'ຕິດຕໍ່ໂຮງຮຽນ',
    'getInTouch': 'ຕິດຕໍ່',
    'findUsOnline': 'ຊ່ອງທາງອອນໄລນ໌',
    'phone1Label': 'ເບີໂທ 1',
    'phone2Label': 'ເບີໂທ 2',
    'branchCode': 'ລະຫັດສາຂາ',
    'governanceBranchId': 'ເລກສາຂາທາງການ',
    'location': 'ທີ່ຕັ້ງ',
    'googleMaps': 'Google Maps',
    'facebook': 'Facebook',
    'website': 'ເວັບໄຊ',
    'schoolBranch': 'ສາຂາໂຮງຮຽນ',
    'copied': 'ຄັດລອກແລ້ວ',
    'couldNotOpenLink': 'ບໍ່ສາມາດເປີດລິ້ງນີ້ໄດ້',
    'couldNotLoadSchoolInfo': 'ບໍ່ສາມາດໂຫຼດຂໍ້ມູນໂຮງຮຽນໄດ້',
    'noSchoolInfoAvailable': 'ບໍ່ມີຂໍ້ມູນໂຮງຮຽນ',
    'noBranchLinkedStudent': 'ບໍ່ມີສາຂາທີ່ຜູກກັບນັກຮຽນຄົນນີ້.',
    'homeTab': 'ໜ້າຫຼັກ',
    'classroomTab': 'ຫ້ອງຮຽນ',
    'studyResultTab': 'ຜົນການຮຽນ',
    'feeTab': 'ຄ່າທຳນຽມ',
    'scoreTab': 'ຄະແນນ',
    'settingsTab': 'ຕັ້ງຄ່າ',
    'homeCreateTask': 'ສ້າງວຽກ',
    'homeQuickPayment': 'ຊຳລະເງິນດ່ວນ',
    'homeNewAppointment': 'ນັດໝາຍໃໝ່',
    'couldNotLoadParentSession': 'ບໍ່ສາມາດໂຫຼດເຊດຊັນຜູ້ປົກຄອງໄດ້.',
    'noApprovedStudentsFound': 'ບໍ່ພົບນັກຮຽນທີ່ອະນຸມັດແລ້ວ.',
    'couldNotLoadStudents': 'ບໍ່ສາມາດໂຫຼດນັກຮຽນໄດ້',
    'classNotAssigned': 'ຍັງບໍ່ໄດ້ກຳນົດຫ້ອງຮຽນ',
    'notifications': 'ແຈ້ງເຕືອນ',
    'noNotifications': 'ບໍ່ມີແຈ້ງເຕືອນ',
    'noNotificationsHint': 'ແຈ້ງເຕືອນໃໝ່ຈະສະແດງຢູ່ບ່ອນນີ້.',
    'notification': 'ແຈ້ງເຕືອນ',
    'unread': 'ຍັງບໍ່ອ່ານ',
    'read': 'ອ່ານແລ້ວ',
    'unreadCount': '{count} ຍັງບໍ່ອ່ານ',
    'allCaughtUp': 'ອ່ານຄົບແລ້ວ',
    'trySwitchingFilter': 'ລອງປ່ຽນຕົວກອງ.',
    'copy': 'ຄັດລອກ',
    'details': 'ລາຍລະອຽດ',
    'markAsRead': 'ໝາຍວ່າອ່ານແລ້ວ',
    'markAsUnread': 'ໝາຍວ່າຍັງບໍ່ອ່ານ',
    'viewAll': 'ເບິ່ງທັງໝົດ',
    'tapOutsideToClose': 'ແຕະດ້ານນອກເພື່ອປິດ',
    'recent': 'ຫຼ້າສຸດ',
    'none': '-',
    'today': 'ມື້ນີ້',
    'yesterday': 'ມື້ວານນີ້',
    'thisWeek': 'ອາທິດນີ້',
    'earlier': 'ກ່ອນໜ້ານີ້',
    'checkInLate': 'ເຊັກອິນຊ້າ',
    'checkedIn': 'ເຊັກອິນແລ້ວ',
    'notCheckedIn': 'ຍັງບໍ່ໄດ້ເຊັກອິນ',
    'attendanceTracking': 'ຕິດຕາມການມາໂຮງຮຽນ',
    'participationScore': 'ຄະແນນການມີສ່ວນຮ່ວມ',
    'commonEraPrefix': 'ຄ.ສ.',
    'monthJanuary': 'ມັງກອນ',
    'monthFebruary': 'ກຸມພາ',
    'monthMarch': 'ມີນາ',
    'monthApril': 'ເມສາ',
    'monthMay': 'ພຶດສະພາ',
    'monthJune': 'ມິຖຸນາ',
    'monthJuly': 'ກໍລະກົດ',
    'monthAugust': 'ສິງຫາ',
    'monthSeptember': 'ກັນຍາ',
    'monthOctober': 'ຕຸລາ',
    'monthNovember': 'ພະຈິກ',
    'monthDecember': 'ທັນວາ',
    'eventAndAnnouncement': 'ກິດຈະກຳ ແລະ ແຈ້ງການ',
    'attendanceAndCalendar': 'ການມາໂຮງຮຽນ ແລະ ປະຕິທິນ',
    'laoNewYear2026': 'ປີໃໝ່ລາວ 2026',
    'allMenus': 'ເມນູທັງໝົດ',
    'schoolContact': 'ຕິດຕໍ່ໂຮງຮຽນ',
    'savingDeposit': 'ເງິນຝາກປະຢັດ',
    'savings': 'ເງິນຝາກປະຢັດ',
    'studentSavingActivity': 'ການເຄື່ອນໄຫວເງິນຝາກນັກຮຽນ',
    'yourChild': 'ລູກຂອງທ່ານ',
    'personalSavings': 'ສ່ວນບຸກຄົນ',
    'classroomSavings': 'ຫ້ອງຮຽນ',
    'transaction': 'ລາຍການ',
    'amountBalance': 'ຈຳນວນເງິນ / ຍອດເຫຼືອ',
    'noDataInSelectedRange': 'ບໍ່ມີຂໍ້ມູນໃນຊ່ວງທີ່ເລືອກ',
    'tryAnotherDateRangeOrRefresh': 'ລອງເລືອກຊ່ວງວັນທີອື່ນ ຫຼື ໂຫຼດໜ້າໃໝ່.',
    'latestDeposit': 'ຍອດຝາກຫຼ້າສຸດ',
    'depositMovement': 'ຍອດເຄື່ອນໄຫວຝາກ',
    'withdrawalMovement': 'ຍອດເຄື່ອນໄຫວຖອນ',
    'available': 'ໃຊ້ໄດ້',
    'nonAvailable': 'ຍັງໃຊ້ບໍ່ໄດ້',
    'endingBalance': 'ຍອດເຫຼືອທ້າຍ',
    'withdrawMoney': 'ຖອນເງິນ',
    'deposit': 'ຝາກເງິນ',
    'withdrawal': 'ຖອນເງິນ',
    'pendingWithdrawal': 'ລໍຖ້າອະນຸມັດຖອນເງິນ',
    'withdrawUpper': 'ຖອນເງິນ',
    'trackingUpper': 'ຕິດຕາມ',
    'cashReceived': 'ຮັບເງິນແລ້ວ',
    'schoolReleasedWithdrawal': 'ໂຮງຮຽນໄດ້ຈ່າຍເງິນຖອນຂອງທ່ານແລ້ວ.',
    'completedUpper': 'ສຳເລັດແລ້ວ',
    'requestRejected': 'ຄຳຂໍຖືກປະຕິເສດ',
    'schoolCouldNotProcessWithdrawal':
        'ໂຮງຮຽນບໍ່ສາມາດດຳເນີນການຖອນເງິນນີ້ໄດ້. ກະລຸນາຕິດຕໍ່ຫ້ອງການເພື່ອຂໍລາຍລະອຽດ.',
    'approvedReadyForPickup': 'ອະນຸມັດແລ້ວ — ພ້ອມຮັບເງິນ',
    'visitOfficeCollectCash':
        'ກະລຸນາໄປຫ້ອງການໂຮງຮຽນເພື່ອຮັບເງິນ. ຄູຈະມອບໃຫ້ ແລະ ຢືນຢັນ.',
    'readyForPickupUpper': 'ພ້ອມຮັບເງິນ',
    'adminConfirmed': 'ຜູ້ດູແລຢືນຢັນແລ້ວ',
    'requestForwardedSuperAdmin':
        'ຄຳຂໍຂອງທ່ານຖືກກວດແລະສົ່ງຕໍ່ໄປຫາຜູ້ດູແລສູງສຸດເພື່ອອະນຸມັດຂັ້ນສຸດທ້າຍ.',
    'waitingSuperAdminUpper': 'ລໍຖ້າຜູ້ດູແລສູງສຸດ',
    'sendSuccessfully': 'ສົ່ງສຳເລັດ',
    'withdrawalRequestReceived':
        'ລະບົບໄດ້ຮັບຄຳຂໍຖອນເງິນຂອງທ່ານແລ້ວ. ໂຮງຮຽນຈະກວດສອບໃນໄວໆນີ້.',
    'pendingReviewUpper': 'ລໍຖ້າກວດສອບ',
    'requestReceivedBySystem': 'ລະບົບໄດ້ຮັບຄຳຂໍແລ້ວ',
    'waitingAdminConfirm': 'ລໍຖ້າຜູ້ດູແລຢືນຢັນ',
    'forwardedToSuperAdmin': 'ສົ່ງຕໍ່ໄປຫາຜູ້ດູແລສູງສຸດ',
    'superAdminApproved': 'ຜູ້ດູແລສູງສຸດອະນຸມັດແລ້ວ',
    'withdrawalComplete': 'ຖອນເງິນສຳເລັດ',
    'contactSchoolNextSteps': 'ຕິດຕໍ່ໂຮງຮຽນເພື່ອຂັ້ນຕອນຕໍ່ໄປ',
    'backToSavings': 'ກັບໄປໜ້າເງິນຝາກ',
    'checkStatus': 'ກວດສະຖານະ',
    'close': 'ປິດ',
    'allTransactions': 'ລາຍການທັງໝົດ',
    'anyDate': 'ທຸກວັນທີ',
    'search': 'ຄົ້ນຫາ',
    'retry': 'ລອງໃໝ່',
    'studentIdUnavailableSelectStudentAgain':
        'ບໍ່ພົບ ID ນັກຮຽນ. ກະລຸນາເລືອກນັກຮຽນໃໝ່.',
    'unableToWithdraw': 'ບໍ່ສາມາດຖອນເງິນໄດ້',
    'noAvailableBalanceToWithdraw': 'ຍັງບໍ່ມີຍອດເງິນທີ່ຖອນໄດ້.',
    'loadingWithdrawalReasons': 'ກຳລັງໂຫຼດເຫດຜົນການຖອນ...',
    'noActiveWithdrawalReason': 'ໂຮງຮຽນຍັງບໍ່ໄດ້ຕັ້ງເຫດຜົນການຖອນທີ່ໃຊ້ງານ.',
    'withdraw': 'ຖອນເງິນ',
    'amountNotAvailable': 'ຈຳນວນເງິນຖອນບໍ່ໄດ້',
    'youCanWithdrawUpToOnly': 'ທ່ານສາມາດຖອນໄດ້ສູງສຸດ {amount} ເທົ່ານັ້ນ.',
    'confirmWithdrawal': 'ຢືນຢັນການຖອນ',
    'requestWithdrawalOf': 'ຂໍຖອນເງິນ {amount}?',
    'submittingWithdrawalRequest': 'ກຳລັງສົ່ງຄຳຂໍຖອນ...',
    'withdrawalFailed': 'ຖອນເງິນບໍ່ສຳເລັດ',
    'amountToWithdraw': 'ຈຳນວນເງິນທີ່ຈະຖອນ',
    'tellSchoolWithdrawalAmount': 'ແຈ້ງໂຮງຮຽນວ່າຕ້ອງການຖອນເທົ່າໃດ.',
    'nonAvailableFundsHelp':
        'ເງິນທີ່ຍັງໃຊ້ບໍ່ໄດ້ແມ່ນເງິນຝາກທີ່ທະນາຄານຍັງບໍ່ຢືນຢັນ ແລະ ຍັງຖອນບໍ່ໄດ້.',
    'optional': 'ບໍ່ບັງຄັບ',
    'enterAmountGreaterThanZero': 'ປ້ອນຈຳນວນເງິນຫຼາຍກວ່າສູນ',
    'exceedsAvailableBalance': 'ເກີນຍອດເງິນທີ່ຖອນໄດ້',
    'percentOfAvailable': '{percent}% ຂອງຍອດທີ່ຖອນໄດ້',
    'anythingSchoolShouldKnow': 'ມີຫຍັງແຈ້ງໂຮງຮຽນບໍ?',
    'continueAction': 'ດຳເນີນຕໍ່',
    'newsAndActivities': 'ຂ່າວ ແລະ ກິດຈະກຳ',
    'photoGallery': 'ຄັງຮູບພາບ',
    'gallery': 'ຄັງຮູບພາບ',
    'allPosts': 'ໂພສທັງໝົດ',
    'publicPosts': 'ໂພສສາທາລະນະ',
    'individualPosts': 'ໂພສສ່ວນຕົວ',
    'searchPostsEventsAlbums': 'ຄົ້ນຫາໂພສ, ກິດຈະກຳ ຫຼື ອັນບັ້ມ...',
    'privatePhotosSharedWithFamily':
        'ຮູບສ່ວນຕົວແບ່ງປັນໂດຍຄູ ແລະ ເຫັນໄດ້ສະເພາະຄອບຄົວຂອງທ່ານ.',
    'sharedPrivatelyWithFamily': 'ແບ່ງປັນສ່ວນຕົວກັບຄອບຄົວຂອງທ່ານ',
    'studentsTagged': 'ແທັກນັກຮຽນ {count} ຄົນ',
    'private': 'ສ່ວນຕົວ',
    'public': 'ສາທາລະນະ',
    'noGalleryPostsYet': 'ຍັງບໍ່ມີ {tab}',
    'newSchoolMomentsAppearHere': 'ຊ່ວງເວລາຂອງໂຮງຮຽນຈະສະແດງຢູ່ນີ້.',
    'couldNotLoadGallery': 'ຕອນນີ້ໂຫຼດຄັງຮູບພາບບໍ່ໄດ້.',
    'schoolMoment': 'ຊ່ວງເວລາໂຮງຮຽນ',
    'justNow': 'ດຽວນີ້',
    'minutesAgo': '{count} ນາທີກ່ອນ',
    'hoursAgo': '{count} ຊົ່ວໂມງກ່ອນ',
    'daysAgo': '{count} ມື້ກ່ອນ',
    'unableToSendComment': 'ສົ່ງຄອມເມັນບໍ່ໄດ້. ກະລຸນາລອງໃໝ່.',
    'imageDownloadedSuccessfully': 'ດາວໂຫຼດຮູບສຳເລັດ.',
    'unableToDownloadImage': 'ດາວໂຫຼດຮູບນີ້ບໍ່ໄດ້.',
    'downloadImage': 'ດາວໂຫຼດຮູບ',
    'likeCountOne': '{count} ຖືກໃຈ',
    'likeCountMany': '{count} ຖືກໃຈ',
    'commentCountOne': '{count} ຄອມເມັນ',
    'commentCountMany': '{count} ຄອມເມັນ',
    'commentsCount': 'ຄອມເມັນ ({count})',
    'category': 'ໝວດໝູ່',
    'audience': 'ຜູ້ເຫັນ',
    'yourFamily': 'ຄອບຄົວຂອງທ່ານ',
    'schoolCommunity': 'ຊຸມຊົນໂຮງຮຽນ',
    'shared': 'ແບ່ງປັນ',
    'noCommentsYetStartConversation': 'ຍັງບໍ່ມີຄອມເມັນ. ເລີ່ມສົນທະນາໄດ້ເລີຍ!',
    'replyingToName': 'ຕອບກັບ {name}',
    'replyingToComment': 'ກຳລັງຕອບຄອມເມັນ',
    'writeAComment': 'ຂຽນຄອມເມັນ...',
    'appointments': 'ນັດໝາຍ',
    'calendar': 'ປະຕິທິນ',
    'scheduleAppointments': 'ຕາຕະລາງ ແລະ ນັດໝາຍ',
    'filter': 'ກັ່ນຕອງ',
    'filterByStatus': 'ກັ່ນຕອງຕາມສະຖານະ',
    'all': 'ທັງໝົດ',
    'confirmed': 'ຢືນຢັນແລ້ວ',
    'cancelled': 'ຍົກເລີກແລ້ວ',
    'postponed': 'ເລື່ອນແລ້ວ',
    'pending': 'ລໍຖ້າ',
    'accepted': 'ຍອມຮັບແລ້ວ',
    'rescheduled': 'ເລື່ອນນັດແລ້ວ',
    'teacher': 'ຄູ',
    'admin': 'ແອັດມິນ',
    'superAdmin': 'ຊູເປີແອັດມິນ',
    'superSuperAdmin': 'ຊູເປີຊູເປີແອັດມິນ',
    'parent': 'ຜູ້ປົກຄອງ',
    'confirm': 'ຢືນຢັນ',
    'delete': 'ລຶບ',
    'reschedule': 'ເລື່ອນນັດ',
    'timeline': 'ລຳດັບເຫດການ',
    'noMoreAppointmentsToday': 'ມື້ນີ້ບໍ່ມີນັດໝາຍເພີ່ມແລ້ວ',
    'allCaughtUpEnjoyDay': 'ທຸກຢ່າງຄົບແລ້ວ. ຂໍໃຫ້ເປັນມື້ທີ່ດີ.',
    'loadingAppointments': 'ກຳລັງໂຫຼດນັດໝາຍ...',
    'couldNotLoadAppointments': 'ໂຫຼດນັດໝາຍບໍ່ໄດ້',
    'confirmAppointment': 'ຢືນຢັນນັດໝາຍ',
    'confirmAppointmentQuestion': 'ຢືນຢັນ',
    'scheduledOn': 'ທີ່ນັດໄວ້ວັນທີ',
    'confirming': 'ກຳລັງຢືນຢັນ...',
    'confirmedSuccessTitle': 'ຢືນຢັນແລ້ວ!',
    'appointmentConfirmedSuccessfully': 'ຢືນຢັນນັດໝາຍສຳເລັດແລ້ວ.',
    'failed': 'ບໍ່ສຳເລັດ',
    'couldNotConfirmAppointment': 'ຢືນຢັນນັດໝາຍບໍ່ໄດ້. ກະລຸນາລອງໃໝ່.',
    'confirmReschedule': 'ຢືນຢັນການເລື່ອນນັດ',
    'moveAppointmentTo': 'ຍ້າຍນັດໝາຍໄປວັນທີ',
    'rescheduling': 'ກຳລັງເລື່ອນນັດ...',
    'rescheduledSuccessTitle': 'ເລື່ອນນັດແລ້ວ!',
    'appointmentMovedTo': 'ນັດໝາຍຖືກຍ້າຍໄປວັນທີ',
    'couldNotRescheduleAppointment': 'ເລື່ອນນັດໝາຍບໍ່ໄດ້. ກະລຸນາລອງໃໝ່.',
    'deleteAppointment': 'ລຶບນັດໝາຍ',
    'declineAppointment': 'ປະຕິເສດນັດໝາຍ',
    'decline': 'ປະຕິເສດ',
    'keep': 'ເກັບໄວ້',
    'deleting': 'ກຳລັງລຶບ...',
    'declining': 'ກຳລັງປະຕິເສດ...',
    'appointmentDeleted': 'ລຶບນັດໝາຍແລ້ວ',
    'appointmentDeclined': 'ປະຕິເສດນັດໝາຍແລ້ວ',
    'couldNotDeleteAppointment': 'ລຶບນັດໝາຍບໍ່ໄດ້. ກະລຸນາລອງໃໝ່.',
    'couldNotDeclineAppointment': 'ປະຕິເສດນັດໝາຍບໍ່ໄດ້. ກະລຸນາລອງໃໝ່.',
    'savingAppointment': 'ກຳລັງບັນທຶກນັດໝາຍ...',
    'appointmentCreated': 'ສ້າງນັດໝາຍແລ້ວ',
    'appointmentSavedSuccessfully': 'ບັນທຶກນັດໝາຍສຳເລັດແລ້ວ.',
    'couldNotSaveAppointment': 'ບັນທຶກນັດໝາຍບໍ່ໄດ້. ກະລຸນາລອງໃໝ່.',
    'activityTimeline': 'ລຳດັບເຫດການ',
    'updateSingular': 'ອັບເດດ',
    'updatePlural': 'ອັບເດດ',
    'noTimelineActivityYet': 'ຍັງບໍ່ມີກິດຈະກຳໃນລຳດັບເຫດການ.',
    'appointmentRecordCreated': 'ສ້າງບັນທຶກນັດໝາຍ',
    'created': 'ສ້າງແລ້ວ',
    'createdBy': 'ສ້າງໂດຍ',
    'titleLabel': 'ຫົວຂໍ້',
    'scheduleRecorded': 'ບັນທຶກຕາຕະລາງແລ້ວ',
    'time': 'ເວລາ',
    'participantInvited': 'ເຊີນຜູ້ເຂົ້າຮ່ວມແລ້ວ',
    'addedAsParticipant': 'ຖືກເພີ່ມເປັນຜູ້ເຂົ້າຮ່ວມ',
    'initialStatus': 'ສະຖານະເລີ່ມຕົ້ນ',
    'appointmentRescheduled': 'ເລື່ອນນັດໝາຍແລ້ວ',
    'newSchedule': 'ຕາຕະລາງໃໝ່',
    'previous': 'ກ່ອນໜ້າ',
    'participantNotifiedOfNewSchedule': 'ແຈ້ງຕາຕະລາງໃໝ່ໃຫ້ຜູ້ເຂົ້າຮ່ວມແລ້ວ',
    'newScheduleSharedWith': 'ແບ່ງປັນຕາຕະລາງໃໝ່ກັບ',
    'rescheduleRequested': 'ຮ້ອງຂໍເລື່ອນນັດ',
    'participantDeclined': 'ຜູ້ເຂົ້າຮ່ວມປະຕິເສດ',
    'participantAccepted': 'ຜູ້ເຂົ້າຮ່ວມຍອມຮັບ',
    'requestedDifferentSchedule': 'ຮ້ອງຂໍຕາຕະລາງອື່ນ',
    'responseChangedTo': 'ປ່ຽນຄຳຕອບເປັນ',
    'by': 'ໂດຍ',
    'proposed': 'ສະເໜີ',
    'attempts': 'ຈຳນວນຄັ້ງ',
    'moreDetailSingular': 'ລາຍລະອຽດເພີ່ມ',
    'moreDetailPlural': 'ລາຍລະອຽດເພີ່ມ',
    'timeNotRecorded': 'ບໍ່ມີບັນທຶກເວລາ',
    'pickNewDateTime': 'ເລືອກວັນທີ ແລະ ເວລາໃໝ່',
    'newDate': 'ວັນທີໃໝ່',
    'newTime': 'ເວລາໃໝ່',
    'start': 'ເລີ່ມ',
    'end': 'ສິ້ນສຸດ',
    'newAppointment': 'ນັດໝາຍໃໝ່',
    'parentTeacherMeetingHint': 'ຕົວຢ່າງ: ປະຊຸມຜູ້ປົກຄອງ-ຄູ',
    'startAt': 'ເລີ່ມເວລາ',
    'endAt': 'ສິ້ນສຸດເວລາ',
    'meetingPlaceOptional': 'ສະຖານທີ່ນັດໝາຍ (ບໍ່ບັງຄັບ)',
    'addMeetingPlace': 'ເພີ່ມສະຖານທີ່ນັດໝາຍ...',
    'inviteParentsOptional': 'ເຊີນຜູ້ປົກຄອງ (ບໍ່ບັງຄັບ)',
    'employeesRequired': 'ພະນັກງານ *',
    'saveAppointment': 'ບັນທຶກນັດໝາຍ',
    'loadingEmployees': 'ກຳລັງໂຫຼດພະນັກງານ...',
    'selectEmployees': 'ເລືອກພະນັກງານ',
    'loadingParents': 'ກຳລັງໂຫຼດຜູ້ປົກຄອງ...',
    'inviteParents': 'ເຊີນຜູ້ປົກຄອງ',
    'pleaseSelectAtLeastOneEmployee': 'ກະລຸນາເລືອກພະນັກງານຢ່າງນ້ອຍ 1 ຄົນ',
    'alreadyBooked': 'ມີນັດແລ້ວ',
    'byParent': 'ຕາມຜູ້ປົກຄອງ',
    'byStudent': 'ຕາມນັກຮຽນ',
    'searchStudentByName': 'ຄົ້ນຫານັກຮຽນຕາມຊື່...',
    'searchParentByName': 'ຄົ້ນຫາຜູ້ປົກຄອງຕາມຊື່...',
    'noParentsFound': 'ບໍ່ພົບຜູ້ປົກຄອງ.',
    'typeStudentNameToFindParents': 'ພິມຊື່ນັກຮຽນເພື່ອຄົ້ນຫາຜູ້ປົກຄອງ.',
    'noStudentsFound': 'ບໍ່ພົບນັກຮຽນ.',
    'deselectAll': 'ຍົກເລີກທັງໝົດ',
    'selectAll': 'ເລືອກທັງໝົດ',
    'noParentsLinked': 'ບໍ່ມີຜູ້ປົກຄອງທີ່ຜູກໄວ້',
    'selectTime': 'ເລືອກເວລາ',
    'endTimeMustBeAfterStartTime': 'ເວລາສິ້ນສຸດຕ້ອງຫຼັງເວລາເລີ່ມ',
    'pleaseEnterTitle': 'ກະລຸນາໃສ່ຫົວຂໍ້',
    'timeConflict': 'ເວລາຊ້ອນກັນ',
    'someInviteesAlreadyBooked': 'ຜູ້ຖືກເຊີນບາງຄົນມີນັດໃນເວລານີ້ແລ້ວ.',
    'you': 'ທ່ານ',
    'noEmployeesSelected': 'ຍັງບໍ່ໄດ້ເລືອກພະນັກງານ',
    'employeeSelected': 'ພະນັກງານຖືກເລືອກ',
    'employeesSelected': 'ພະນັກງານຖືກເລືອກ',
    'noParentsInvited': 'ຍັງບໍ່ໄດ້ເຊີນຜູ້ປົກຄອງ',
    'parentInvited': 'ຜູ້ປົກຄອງຖືກເຊີນ',
    'parentsInvited': 'ຜູ້ປົກຄອງຖືກເຊີນ',
    'createAppointment': 'ສ້າງນັດໝາຍ',
    'create': 'ສ້າງ',
    'tasks': 'ວຽກທີ່ມອບໝາຍ',
    'submit': 'ສົ່ງ',
    'upload': 'ອັບໂຫຼດ',
    'openChat': 'ເປີດແຊັດ',
    'score': 'ຄະແນນ',
    'progress': 'ຄວາມຄືບໜ້າ',
    'description': 'ລາຍລະອຽດ',
    'attachments': 'ໄຟລ໌ແນບ',
    'taskDetail': 'ລາຍລະອຽດວຽກ',
    'moreOptionsComingSoon': 'ຕົວເລືອກເພີ່ມເຕີມຈະມາໃນໄວໆນີ້',
    'assignedBy': 'ມອບໝາຍໂດຍ',
    'notGraded': 'ຍັງບໍ່ໄດ້ໃຫ້ຄະແນນ',
    'practiceTarget': 'ເປົ້າໝາຍການຝຶກ',
    'yourProgress': 'ຄວາມຄືບໜ້າຂອງທ່ານ',
    'submissionPlanRounds': 'ແຜນການສົ່ງ · {count} ຮອບ',
    'checkpointsSubmitted': 'ສົ່ງແລ້ວ {submitted} ຈາກ {total} ຈຸດກວດ',
    'lateSubmitted': 'ສົ່ງຊ້າ',
    'earlySubmitted': 'ສົ່ງກ່ອນເວລາ',
    'missed': 'ບໍ່ໄດ້ສົ່ງ',
    'waitingToSubmit': 'ລໍຖ້າສົ່ງ',
    'pointsSuffix': 'ຄະແນນ',
    'waitingForThisCheckpoint': 'ລໍຖ້າສົ່ງຈຸດກວດນີ້',
    'sentDate': 'ສົ່ງແລ້ວ {date}',
    'reviewedDate': 'ກວດແລ້ວ {date}',
    'notStarted': 'ຍັງບໍ່ເລີ່ມ',
    'teacherMarkedTaskComplete': 'ຄູໄດ້ໝາຍວຽກນີ້ວ່າສຳເລັດແລ້ວ.',
    'teacherProgressMessage': 'ຄູລະບຸວ່າທ່ານເຮັດວຽກນີ້ໄດ້ {progress}%.',
    'teacherNoProgressYet': 'ຄູຍັງບໍ່ໄດ້ບັນທຶກຄວາມຄືບໜ້າຂອງວຽກນີ້.',
    'noDescriptionProvided': 'ບໍ່ມີລາຍລະອຽດ.',
    'noAttachments': 'ບໍ່ມີໄຟລ໌ແນບ',
    'filesCount': '{count} ໄຟລ໌',
    'teacherHasNotAddedFiles': 'ຄູຍັງບໍ່ໄດ້ແນບໄຟລ໌.',
    'tapToViewAllAttachments': 'ແຕະເພື່ອເບິ່ງໄຟລ໌ແນບທັງໝົດ',
    'toSubmit': 'ສິ່ງທີ່ຕ້ອງສົ່ງ',
    'photoOfCompletedWork': 'ຮູບວຽກທີ່ເຮັດສຳເລັດ',
    'uploadClearPhotosOrPdf': 'ອັບໂຫຼດຮູບທີ່ຊັດເຈນ ຫຼື PDF.',
    'couldNotOpenNamedFile': 'ບໍ່ສາມາດເປີດ {name} ໄດ້',
    'submissionRoundLocked': 'ຮອບການສົ່ງນີ້ຖືກລັອກ. ກະລຸນາເລືອກຮອບທີ່ເປີດຢູ່.',
    'missingStudent': 'ບໍ່ພົບນັກຮຽນ',
    'noStudentSelectedForTask': 'ບໍ່ໄດ້ເລືອກນັກຮຽນສຳລັບວຽກນີ້.',
    'uploading': 'ກຳລັງອັບໂຫຼດ...',
    'uploaded': 'ອັບໂຫຼດແລ້ວ',
    'fileSubmittedSuccessfully': 'ສົ່ງ {name} ສຳເລັດແລ້ວ.',
    'fileSubmittedForCheckpoint': 'ສົ່ງ {name} ສຳລັບຈຸດກວດ {index} ແລ້ວ.',
    'uploadFailed': 'ອັບໂຫຼດບໍ່ສຳເລັດ',
    'fromTeacherCount': 'ຈາກຄູ ({count})',
    'fromYouCount': 'ຈາກທ່ານ ({count})',
    'filesFromTeacher': 'ໄຟລ໌ຈາກຄູ',
    'teacherHasNotUploadedFiles': 'ຄູຍັງບໍ່ໄດ້ອັບໂຫຼດໄຟລ໌ສຳລັບວຽກນີ້.',
    'yourSubmittedFiles': 'ໄຟລ໌ທີ່ທ່ານສົ່ງແລ້ວ',
    'youHaveNotSubmittedFiles': 'ທ່ານຍັງບໍ່ໄດ້ສົ່ງໄຟລ໌ສຳລັບວຽກນີ້.',
    'submissionPlan': 'ແຜນການສົ່ງ',
    'nextCheckpointSelectedAutomatically':
        'ຈຸດກວດທີ່ສາມາດສົ່ງໄດ້ຖັດໄປຖືກເລືອກອັດຕະໂນມັດ.',
    'submitYourWork': 'ສົ່ງວຽກຂອງທ່ານ',
    'uploadYourWorkHere': 'ອັບໂຫຼດວຽກຂອງທ່ານທີ່ນີ້',
    'photosPdfOrOtherFiles': 'ຮູບພາບ, PDF ຫຼື ໄຟລ໌ອື່ນໆ',
    'chooseFile': 'ເລືອກໄຟລ໌',
    'readyToUpload': 'ພ້ອມອັບໂຫຼດ',
    'pdfFile': 'ໄຟລ໌ PDF',
    'image': 'ຮູບພາບ',
    'video': 'ວິດີໂອ',
    'document': 'ເອກະສານ',
    'file': 'ໄຟລ໌',
    'chooseFromGallery': 'ເລືອກຈາກຄັງຮູບ',
    'choosePdfDocFile': 'ເລືອກໄຟລ໌ (PDF, DOC)',
    'documents': 'ເອກະສານ',
    'previewSupportsImagesPdf': 'ການສະແດງຕົວຢ່າງຮອງຮັບຮູບພາບ ແລະ PDF.',
    'closePreview': 'ປິດຕົວຢ່າງ',
    'taskChat': 'ແຊັດວຽກ',
    'notSignedIn': 'ຍັງບໍ່ໄດ້ເຂົ້າລະບົບ',
    'signInAgainToSendMessages': 'ກະລຸນາເຂົ້າລະບົບໃໝ່ເພື່ອສົ່ງຂໍ້ຄວາມ.',
    'messageNotSent': 'ສົ່ງຂໍ້ຄວາມບໍ່ສຳເລັດ',
    'checkConnectionTryAgain': 'ກະລຸນາກວດກາການເຊື່ອມຕໍ່ ແລ້ວລອງໃໝ່.',
    'reactionFailedTryAgain': 'ກົດສະແດງຄວາມຮູ້ສຶກບໍ່ສຳເລັດ. ກະລຸນາລອງໃໝ່.',
    'originalMessageNotFound': 'ບໍ່ພົບຂໍ້ຄວາມຕົ້ນສະບັບ.',
    'chatFiles': 'ໄຟລ໌ແຊັດ',
    'couldNotSelectFile': 'ບໍ່ສາມາດເລືອກໄຟລ໌ນີ້ໄດ້.',
    'attachmentNotSent': 'ສົ່ງໄຟລ໌ແນບບໍ່ສຳເລັດ.',
    'microphonePermissionRequired': 'ຕ້ອງອະນຸຍາດໃຊ້ໄມໂຄຣໂຟນ.',
    'replyingToMessage': 'ກຳລັງຕອບ {sender}: {message}',
    'typeMessage': 'ພິມຂໍ້ຄວາມ...',
    'couldNotLoadMessages': 'ໂຫຼດຂໍ້ຄວາມບໍ່ໄດ້',
    'noMessagesYet': 'ຍັງບໍ່ມີຂໍ້ຄວາມ',
    'sendMessageStartTeacherConversation': 'ສົ່ງຂໍ້ຄວາມເພື່ອເລີ່ມສົນທະນາກັບຄູ.',
    'reply': 'ຕອບ',
    'deleteMessage': 'ລຶບຂໍ້ຄວາມ',
    'react': 'ສະແດງຄວາມຮູ້ສຶກ',
    'attachment': 'ໄຟລ໌ແນບ',
    'assigned': 'ມອບໝາຍແລ້ວ',
    'inProgress': 'ກຳລັງເຮັດ',
    'completed': 'ສຳເລັດແລ້ວ',
    'couldNotLoadTasks': 'ໂຫຼດວຽກບໍ່ໄດ້',
    'chooseStudentTasksHint': 'ເລືອກນັກຮຽນຈາກໜ້າຫຼັກເພື່ອເບິ່ງວຽກຂອງລາວ.',
    'couldNotLoadTimetable': 'ໂຫຼດຕາຕະລາງຮຽນບໍ່ໄດ້.',
    'noClassesScheduledForThisDay': 'ມື້ນີ້ບໍ່ມີຫ້ອງຮຽນຕາມຕາຕະລາງ.',
    'classTimetable': 'ຕາຕະລາງຮຽນ',
    'minutesShort': '{count} ນາທີ',
    'filterComingSoon': 'ຕົວກອງຈະມາໃນໄວໆນີ້',
    'calendarComingSoon': 'ປະຕິທິນຈະມາໃນໄວໆນີ້',
    'taskHistoryComingSoon': 'ປະຫວັດວຽກຈະມາໃນໄວໆນີ້',
    'searchTasksHint': 'ຄົ້ນຫາວຽກ...',
    'nothingHereYet': 'ຍັງບໍ່ມີຂໍ້ມູນ',
    'assignedTasksEmptyHint': 'ວຽກທີ່ມອບໝາຍໃຫ້ລູກຂອງທ່ານຈະສະແດງຢູ່ນີ້.',
    'upcomingTasks': 'ວຽກທີ່ກຳນົດສົ່ງ',
    'newLabel': 'ໃໝ່',
    'daysLeftOne': 'ເຫຼືອ {count} ມື້',
    'daysLeftMany': 'ເຫຼືອ {count} ມື້',
    'noDueDate': 'ບໍ່ມີກຳນົດສົ່ງ',
    'keepTrackDueDates': 'ຕິດຕາມກຳນົດສົ່ງ!',
    'submitWorkOnTime': 'ສົ່ງວຽກໃຫ້ທັນເວລາ ແລະ ຕິດຕາມຂໍ້ມູນໃຫ້ທັນສະໄໝ.',
    'viewCalendar': 'ເບິ່ງປະຕິທິນ',
    'noCompletedTasksYet': 'ຍັງບໍ່ມີວຽກທີ່ສຳເລັດ.',
    'tasksCompleted': '{count} {task} ສຳເລັດແລ້ວ.',
    'taskSingular': 'ວຽກ',
    'taskPlural': 'ວຽກ',
    'seeFullHistory': 'ເບິ່ງປະຫວັດທັງໝົດ ->',
    'homework': 'ວຽກບ້ານ',
    'overview': 'ພາບລວມ',
    'homeworkProgress': 'ຄວາມຄືບໜ້າວຽກບ້ານ',
    'homeworkList': 'ລາຍການວຽກບ້ານ',
    'itemSingular': 'ລາຍການ',
    'itemPlural': 'ລາຍການ',
    'overdue': 'ເກີນກຳນົດ',
    'searchHomeworkHint': 'ຄົ້ນຫາວິຊາ / ຊັ້ນ / ຄູ...',
    'due': 'ກຳນົດສົ່ງ',
    'latest': 'ຫຼ້າສຸດ',
    'nearestDue': 'ກຳນົດສົ່ງໃກ້ສຸດ',
    'latestDue': 'ກຳນົດສົ່ງຫຼ້າສຸດ',
    'subjectAZ': 'ວິຊາ A-Z',
    'grade': 'ຊັ້ນ',
    'total': 'ລວມ',
    'received': 'ໄດ້ຮັບ',
    'dueDate': 'ກຳນົດສົ່ງ',
    'viewHomeworkDetails': 'ເບິ່ງລາຍລະອຽດວຽກບ້ານ',
    'submitHomework': 'ສົ່ງວຽກບ້ານ',
    'homeworkDetail': 'ລາຍລະອຽດວຽກບ້ານ',
    'homeworkSubmitted': 'ສົ່ງວຽກບ້ານແລ້ວ',
    'submissionClosed': 'ປິດການສົ່ງແລ້ວ',
    'questions': 'ຄຳຖາມ',
    'tasksInThisHomework': 'ລາຍການວຽກໃນວຽກບ້ານນີ້',
    'couldNotOpenFile': 'ບໍ່ສາມາດເປີດໄຟລ໌ໄດ້',
    'reviewSubmission': 'ກວດເບິ່ງກ່ອນສົ່ງ',
    'homeworkSubmittedSuccessfully': 'ສົ່ງວຽກບ້ານສຳເລັດແລ້ວ.',
    'submissionFailed': 'ສົ່ງບໍ່ສຳເລັດ',
    'confirmSubmission': 'ຢືນຢັນການສົ່ງ',
    'scoreBreakdown': 'ລາຍລະອຽດຄະແນນ',
    'questionShort': 'ຂໍ້ {index}',
    'teacherFeedback': 'ຄຳເຫັນຈາກຄູ',
    'chooseAttachWork': 'ເລືອກວິທີແນບວຽກຂອງທ່ານ.',
    'takePhoto': 'ຖ່າຍຮູບ',
    'uploadFromPhone': 'ອັບໂຫຼດຈາກໂທລະສັບ',
    'totalScore': 'ຄະແນນລວມ',
    'instruction': 'ຄຳແນະນຳ',
    'points': '{score} ຄະແນນ',
    'scoreOutOfPoints': '{score} / {total} ຄະແນນ',
    'save': 'ບັນທຶກ',
    'savingImage': 'ກຳລັງບັນທຶກຮູບ...',
    'imageSaved': 'ບັນທຶກຮູບແລ້ວ',
    'homeworkImageSavedToGallery': 'ບັນທຶກຮູບວຽກບ້ານໄປທີ່ຄັງຮູບພາບແລ້ວ.',
    'homeworkImageSavedSuccessfully': 'ບັນທຶກຮູບວຽກບ້ານສຳເລັດແລ້ວ.',
    'couldNotSaveImage': 'ບໍ່ສາມາດບັນທຶກຮູບໄດ້',
    'couldNotDownloadImage': 'ບໍ່ສາມາດດາວໂຫຼດຮູບໄດ້ ({statusCode}).',
    'imageCouldNotBeSaved': 'ບໍ່ສາມາດບັນທຶກຮູບນີ້ໄດ້.',
    'images': 'ຮູບພາບ',
    'yourScore': 'ຄະແນນຂອງທ່ານ',
    'nothingHere': 'ບໍ່ມີຂໍ້ມູນ',
    'noHomeworkMatchesFilter': 'ບໍ່ມີວຽກບ້ານທີ່ກົງກັບຕົວກອງປັດຈຸບັນ.',
    'couldNotLoadHomework': 'ໂຫຼດວຽກບ້ານບໍ່ໄດ້',
    'noStudentSelected': 'ຍັງບໍ່ໄດ້ເລືອກນັກຮຽນ',
    'pickStudentHomeworkHint':
        'ເລືອກນັກຮຽນຈາກໜ້າຫຼັກ. ຈະສະແດງວຽກບ້ານຂອງຫ້ອງຮຽນນັ້ນເທົ່ານັ້ນ.',
    'specialTasks': 'ວຽກພິເສດ',
    'reports': 'ລາຍງານ',
    'notificationSenderAlphaSchool': 'Alpha School',
    'notificationSenderTeacherLina': 'ຄູ - ນາງ Lina',
    'notificationSenderFinanceOffice': 'ຫ້ອງການການເງິນ',
    'notificationSenderLibrary': 'ຫ້ອງສະໝຸດ',
    'notificationImportantTitle': 'ແຈ້ງການສຳຄັນ',
    'notificationParentMeetingBody': 'ພົບກັນໃນການປະຊຸມຜູ້ປົກຄອງວັນສຸກ 15:00.',
    'notificationHomeworkTitle': 'ວຽກບ້ານ',
    'notificationMathHomeworkBody': 'ສົ່ງວຽກບ້ານຄະນິດສາດກ່ອນ 18:00.',
    'notificationTuitionReminderTitle': 'ແຈ້ງເຕືອນຄ່າຮຽນ',
    'notificationTuitionReminderBody': 'ກະລຸນາຊຳລະຄ່າຮຽນກ່ອນວັນທີ 28.',
    'notificationReturnBookTitle': 'ຄືນປຶ້ມ',
    'notificationReturnBookBody': 'ປຶ້ມທີ່ຢືມຈະຄົບກຳນົດໃນ 2 ມື້.',
    'selectMonth': 'ເລືອກເດືອນ',
    'classroomLabel': 'ຫ້ອງຮຽນ',
    'studentIdLabel': 'ລະຫັດ',
    'allMonths': 'ທຸກເດືອນ',
    'trackStudentAttendance': 'ຕິດຕາມການມາໂຮງຮຽນຂອງນັກຮຽນ',
    'attended': 'ມາຮຽນ',
    'absent': 'ຂາດຮຽນ',
    'daysCountLabel': 'ມື້',
    'date': 'ວັນທີ',
    'reason': 'ເຫດຜົນ',
    'attendanceNote': 'ໝາຍເຫດ',
    'status': 'ສະຖານະ',
    'noAttendanceRecords': 'ບໍ່ມີຂໍ້ມູນການມາຮຽນ',
    'late': 'ມາຊ້າ',
    'normal': 'ປົກກະຕິ',
    'checkIn': 'ເຊັກອິນ',
    'attendancePresent': 'ມາຮຽນ',
    'attendanceEarly': 'ມາໄວ',
    'arrivedEarly': 'ມາຮອດໄວ',
    'onTime': 'ກົງເວລາ',
    'arrivedLate': 'ມາຮອດຊ້າ',
    'recorded': 'ບັນທຶກແລ້ວ',
    'scannedViaQrCode': 'ສະແກນຜ່ານ QR Code',
    'alreadyCheckedIn': 'ເຊັກອິນແລ້ວ',
    'checkedInAt': 'ເຊັກອິນເວລາ',
    'qrCodeAlreadyScannedToday': 'QR Code ນີ້ຖືກສະແກນແລ້ວໃນມື້ນີ້.',
    'scanNextStudent': 'ສະແກນນັກຮຽນຄົນຕໍ່ໄປ',
    'checkInFailed': 'ເຊັກອິນບໍ່ສຳເລັດ',
    'attendanceRuleNotFound': 'ບໍ່ພົບກົດເວລາເຊັກອິນ',
    'scanHistory': 'ປະຫວັດສະແກນ',
    'scannedStudents': 'ສະແກນແລ້ວ',
    'noScanRecords': 'ບໍ່ມີຂໍ້ມູນສະແກນໃນມື້ນີ້.',
    'pleaseSelectStudentFirst': 'ກະລຸນາເລືອກນັກຮຽນກ່ອນ.',
    'loading': 'ກຳລັງໂຫຼດ...',
    'participation': 'ການມີສ່ວນຮ່ວມ',
    'dailyActivityScores': 'ຄະແນນກິດຈະກຳປະຈຳວັນ',
    'activityWeights': 'ນ້ຳໜັກຄະແນນກິດຈະກຳ',
    'selectedDay': 'ມື້ທີ່ເລືອກ',
    'noActivitiesToday': 'ມື້ນີ້ບໍ່ມີກິດຈະກຳ',
    'noActivitiesOnThisDay': 'ບໍ່ມີກິດຈະກຳໃນມື້ນີ້',
    'tryDifferentDayFromCalendar': 'ລອງເລືອກມື້ອື່ນຈາກປະຕິທິນ.',
    'backToToday': 'ກັບໄປມື້ນີ້',
    'selectAStudent': 'ເລືອກນັກຮຽນ',
    'pickStudentParticipationScores':
        'ເລືອກນັກຮຽນຈາກໜ້າຫຼັກເພື່ອເບິ່ງຄະແນນການມີສ່ວນຮ່ວມ.',
    'activityCountOne': '{count} ກິດຈະກຳ',
    'activityCountMany': '{count} ກິດຈະກຳ',
    'couldNotLoadScores': 'ບໍ່ສາມາດໂຫຼດຄະແນນໄດ້',
    'weekdayMonShort': 'ຈັນ',
    'weekdayTueShort': 'ອັງ',
    'weekdayWedShort': 'ພຸດ',
    'weekdayThuShort': 'ພະຫັດ',
    'weekdayFriShort': 'ສຸກ',
    'weekdaySatShort': 'ເສົາ',
    'weekdaySunShort': 'ອາທິດ',
    'monthJanShort': 'ມັງ',
    'monthFebShort': 'ກຸມ',
    'monthMarShort': 'ມີນາ',
    'monthAprShort': 'ເມສາ',
    'monthMayShort': 'ພຶດ',
    'monthJunShort': 'ມິຖຸ',
    'monthJulShort': 'ກໍລະ',
    'monthAugShort': 'ສິງ',
    'monthSepShort': 'ກັນ',
    'monthOctShort': 'ຕຸລາ',
    'monthNovShort': 'ພະຈິ',
    'monthDecShort': 'ທັນວາ',
    'yearCalendar': 'ປະຕິທິນປີ',
    'eventsToday': 'ກິດຈະກຳມື້ນີ້',
    'noEvents': 'ບໍ່ມີກິດຈະກຳ',
    'previewOnlyHint': 'ໜ້ານີ້ເປັນຕົວຢ່າງເທົ່ານັ້ນ.',
    'preview': 'ຕົວຢ່າງ',
    'eventCountOne': '{count} ກິດຈະກຳ',
    'eventCountMany': '{count} ກິດຈະກຳ',
    'pickMonth': 'ເລືອກເດືອນ',
    'eventsOn': 'ກິດຈະກຳໃນວັນທີ',
    'tapDayAboveHint': 'ແຕະມື້ດ້ານເທິງເພື່ອເບິ່ງກິດຈະກຳ.',
    'selected': 'ເລືອກແລ້ວ',
    'type': 'ປະເພດ',
    'title': 'ຫົວຂໍ້',
    'event': 'ກິດຈະກຳ',
    'task': 'ວຽກ',
    'holiday': 'ວັນພັກ',
    'weekdayMonTiny': 'ຈ',
    'weekdayTueTiny': 'ອ',
    'weekdayWedTiny': 'ພ',
    'weekdayThuTiny': 'ພຫ',
    'weekdayFriTiny': 'ສ',
    'weekdaySatTiny': 'ສ',
    'weekdaySunTiny': 'ອາ',
    'weekdayMonCalendar': 'ຈັນ',
    'weekdayTueCalendar': 'ອັງຄານ',
    'weekdayWedCalendar': 'ພຸດ',
    'weekdayThuCalendar': 'ພະຫັດ',
    'weekdayFriCalendar': 'ສຸກ',
    'weekdaySatCalendar': 'ເສົາ',
    'weekdaySunCalendar': 'ອາທິດ',
    'demoCalendarParentMeeting': 'ປະຊຸມຜູ້ປົກຄອງ',
    'demoCalendarParentMeetingNote': 'ຫ້ອງ 2A • 09:00',
    'demoCalendarDesignReview': 'ກວດແບບອອກແບບ',
    'demoCalendarDesignReviewNote': 'ຮ່າງແບນເນີ',
    'demoCalendarSportsDay': 'ວັນກິລາ',
    'demoCalendarSportsDayNote': 'ນຳຊຸດກິລາມາດ້ວຍ',
    'demoCalendarHoliday': 'ວັນພັກ',
    'demoCalendarHolidayNote': 'ໂຮງຮຽນປິດ',
    'demoCalendarVaccinationCheck': 'ກວດວັກຊີນ',
    'demoCalendarVaccinationCheckNote': 'ນຳປຶ້ມສຸຂະພາບມາດ້ວຍ',
    'demoCalendarSystemMaintenance': 'ບຳລຸງຮັກສາລະບົບ',
    'demoCalendarSystemMaintenanceNote': 'ອັບເດດລະບົບ Firebase',
    'demoCalendarNewTermBegins': 'ເປີດພາກຮຽນໃໝ່',
    'demoCalendarNewTermBeginsNote': 'ຍິນດີຕ້ອນຮັບກັບມາ!',
    'demoCalendarYearEndCelebration': 'ງານສະຫຼອງທ້າຍປີ',
    'demoCalendarYearEndCelebrationNote': 'ຫ້ອງປະຊຸມ • 15:00',
    'demoCalendarDecorationSetup': 'ຈັດຕົກແຕ່ງ',
    'demoCalendarDecorationSetupNote': 'ຫ້ອງການດ້ານໜ້າ',
  };
}

class _AppLocalizationsDelegate
    extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) =>
      locale.languageCode == 'en' || locale.languageCode == 'lo';

  @override
  Future<AppLocalizations> load(Locale locale) => AppLocalizations.load(locale);

  @override
  bool shouldReload(_AppLocalizationsDelegate old) => false;
}
